extends RefCounted
## Flag data, converted from the Old Flags React Native app (src/game and src/i18n).
## Each slug names a PNG: flags/old/<slug>.png or flags/classic/<slug>.png.
## Names follow the order of LANGUAGES in strings.gd.

## Historical and defunct state flags, each with its difficulty tier:
## easy   - still resembles a flag known today, or is too iconic to confuse;
## hard   - a repetitive family with no modern anchor (British colonial Blue Ensigns, French colonial
##          ensigns, Soviet / Yugoslav republics, small 19th-century German and Italian states);
## medium - everything else.
const OLD := {
	"reino-portugal": "easy",
	"portugal-reino-unido-brasil": "easy",
	"portugal-restauracao": "easy",
	"macau-governo": "medium",
	"rodesia": "medium",
	"zaire": "medium",
	"polonia-1927": "easy",
	"lituania-rss": "hard",
	"urss": "easy",
	"alemanha-leste": "easy",
	"jugoslavia": "easy",
	"checoslovaquia": "easy",
	"vietname-sul": "medium",
	"confederados-eua": "easy",
	"manchukuo": "medium",
	"italia-reino": "easy",
	"italia-napoleonica": "easy",
	"alemanha-imperial": "easy",
	"egito-reino": "medium",
	"transvaal": "medium",
	"brasil-imperio": "easy",
	"terra-nova": "hard",
	"imperio-romano": "easy",
	"reino-de-franca": "easy",
	"dinastia-qing": "easy",
	"aragao": "easy",
	"veneza": "easy",
	"grao-ducado-lituania": "easy",
	"austria-hungria": "medium",
	"prussia": "medium",
	"portugal-1095": "easy",
	"portugal-descobrimentos": "easy",
	"sacro-imperio-romano": "easy",
	"ordem-teutonica": "easy",
	"augsburgo": "hard",
	"duas-sicilias": "medium",
	"imperio-russo": "medium",
	"imperio-otomano": "easy",
	"imperio-japones": "easy",
	"uniao-sul-africana": "medium",
	"primeiro-imperio-mexicano": "easy",
	"gra-colombia": "easy",
	"polonia-lituania": "hard",
	"eua-13-estrelas": "easy",
	"eua-15-estrelas": "easy",
	"eua-20-estrelas": "easy",
	"eua-48-estrelas": "easy",
	"canada-red-ensign": "medium",
	"mexico-primeira-republica": "easy",
	"argentina-belgrano": "easy",
	"chile-patria-vieja": "easy",
	"peru-1820": "easy",
	"venezuela-1811": "easy",
	"indias-orientais-holandesas": "medium",
	"cruz-de-borgonha": "easy",
	"franca-bourbon": "easy",
	"reino-unido-1707": "easy",
	"inglaterra-sao-jorge": "easy",
	"reino-da-grecia": "easy",
	"imperio-austriaco": "medium",
	"reino-da-hungria": "easy",
	"reino-da-romenia": "easy",
	"reino-da-servia": "easy",
	"reino-da-bulgaria": "easy",
	"libia-jamahiriya": "easy",
	"ducado-varsovia": "hard",
	"westfalia": "hard",
	"danzig": "medium",
	"montenegro-reino": "medium",
	"estados-papais": "medium",
	"sardenha-reino": "hard",
	"grao-ducado-toscana": "hard",
	"protetorado-sarre": "hard",
	"estado-cretense": "hard",
	"noruega-suecia-uniao": "medium",
	"paises-baixos-prinsenvlag": "hard",
	"baden-grao-ducado": "hard",
	"frankfurt-cidade-livre": "hard",
	"oldenburg-grao-ducado": "hard",
	"iugoslavia-reino": "medium",
	"trieste-territorio": "hard",
	"parma-ducado": "hard",
	"modena-ducado": "hard",
	"galicia-lodomeria": "hard",
	"ragusa-republica": "hard",
	"etruria": "hard",
	"lucca-ducado": "hard",
	"roma-republica-1798": "hard",
	"partenopeia": "hard",
	"septinsular": "hard",
	"ilhas-jonicas": "hard",
	"berg-grao-ducado": "hard",
	"oeste-florida": "hard",
	"rio-grande": "hard",
	"china-cinco-cores": "medium",
	"siao-elefante": "medium",
	"raj-britanico": "medium",
	"siquim": "medium",
	"birmania-konbaung": "hard",
	"formosa-republica": "hard",
	"iraque-reino": "medium",
	"iemen-mutawakkilita": "hard",
	"estado-livre-laranja": "medium",
	"biafra": "medium",
	"catanga": "medium",
	"afeganistao-1928": "hard",
	"congo-livre": "medium",
	"hong-kong-britanico": "hard",
	"costa-do-ouro": "hard",
	"guiana-britanica": "hard",
	"rodesia-do-sul": "hard",
	"chipre-britanico": "hard",
	"malta-1943": "medium",
	"mandato-britanico-palestina": "hard",
	"catar-britanico": "hard",
	"trucial-states": "hard",
	"argelia-francesa": "hard",
	"marrocos-1666": "hard",
	"lubeque": "hard",
	"polonia-congresso": "hard",
	"curlandia": "hard",
	"bizancio-paleologo": "medium",
	"cispadana": "hard",
	"principados-unidos": "hard",
	"hesse-grao-ducado": "hard",
	"waldeck": "hard",
	"reuss": "hard",
	"lippe": "hard",
	"saxe-weimar": "hard",
	"estado-livre-fiume": "medium",
	"bielorrusia-nacional": "hard",
	"georgia-democratica": "hard",
	"helvetica-republica": "medium",
	"albania-reino": "medium",
	"montenegro-principado": "hard",
	"transilvania": "hard",
	"valaquia": "hard",
	"moldavia-principado": "hard",
	"rss-ucrania": "hard",
	"rss-bielorrussia": "hard",
	"rss-cazaquistao": "hard",
	"rss-usbequistao": "hard",
	"rss-turcomenistao": "hard",
	"rss-azerbaijao": "hard",
	"rss-armenia": "hard",
	"rss-georgia": "hard",
	"rss-letonia": "hard",
	"rss-estonia": "hard",
	"rss-moldavia": "hard",
	"rss-tajiquistao": "hard",
	"rss-quirguizistao": "hard",
	"rss-macedonia": "hard",
	"rss-eslovenia": "hard",
	"rss-croacia": "hard",
	"rss-bosnia": "hard",
	"rss-servia": "hard",
	"brasil-imperio-1822": "easy",
	"rio-grandense-piratini": "medium",
	"republica-juliana": "hard",
	"yucatao": "hard",
	"centro-americana": "hard",
	"peru-bolivia": "hard",
	"haiti-1803": "medium",
	"mengjiang": "hard",
	"turquestao-oriental": "hard",
	"sarawak": "hard",
	"zanzibar-sultanato": "medium",
	"hatay": "hard",
	"hejaz": "medium",
	"arabia-sul-federacao": "hard",
	"iemen-sul": "medium",
	"malaia-britanica": "hard",
	"indochina-francesa": "hard",
	"ceilao-colonia": "hard",
	"birmania-britanica": "hard",
	"birmania-uniao-1948": "hard",
	"birmania-1974": "medium",
	"afeganistao-1930": "medium",
	"afeganistao-1980": "medium",
	"republica-arabe-unida": "medium",
	"laos-reino": "medium",
	"khmer-republica": "medium",
	"mongolia-rpm": "medium",
	"borneo-norte-britanico": "hard",
	"etiopia-imperio": "medium",
	"libano-mandato": "medium",
	"aden-colonia": "hard",
	"sudao-anglo-egipcio": "hard",
	"somalilandia-britanica": "hard",
	"rodesia-do-norte": "hard",
	"niassalandia": "hard",
	"rodesia-niassalandia": "hard",
	"quenia-colonia": "hard",
	"uganda-protetorado": "hard",
	"tanganhica": "hard",
	"africa-equatorial-francesa": "hard",
	"natal-colonia": "hard",
	"congo-republica-popular": "medium",
	"zimbabwe-rodesia": "medium",
}

## Current national flags of the 195 countries, keyed by ISO 3166-1 alpha-2 code.
const CLASSIC := [
	"za", "ao", "dz", "bj", "bw", "bf", "bi", "cv", "cm", "td", "km", "cg", "cd", "ci", "eg",
	"er", "sz", "et", "ga", "gm", "gh", "gn", "gw", "gq", "dj", "ls", "lr", "ly", "mg", "mw",
	"ml", "ma", "mu", "mr", "mz", "na", "ne", "ng", "ke", "cf", "rw", "st", "sn", "sl", "sc",
	"so", "sd", "ss", "tz", "tg", "tn", "ug", "zm", "zw", "af", "sa", "am", "az", "bd", "bh",
	"bt", "bn", "kh", "qa", "kz", "cn", "cy", "kp", "kr", "ae", "ph", "ge", "in", "id", "ir",
	"iq", "il", "jp", "jo", "kw", "la", "lb", "my", "mv", "mn", "mm", "np", "om", "pk", "kg",
	"sg", "sy", "lk", "th", "tj", "tl", "tm", "tr", "uz", "vn", "ye", "ps", "de", "al", "ad",
	"at", "be", "by", "ba", "bg", "hr", "dk", "sk", "si", "es", "ee", "fi", "fr", "gr", "hu",
	"ie", "is", "it", "lv", "li", "lt", "lu", "mk", "mt", "md", "mc", "me", "no", "nl", "pl",
	"pt", "gb", "cz", "ro", "ru", "sm", "rs", "se", "ch", "ua", "va", "au", "fj", "mh", "sb",
	"ki", "fm", "nr", "nz", "pw", "pg", "ws", "to", "tv", "vu", "ag", "bs", "bb", "bz", "ca",
	"cr", "cu", "dm", "do", "sv", "us", "gd", "gt", "ht", "hn", "jm", "mx", "ni", "pa", "kn",
	"lc", "vc", "tt", "ar", "bo", "br", "cl", "co", "ec", "gy", "py", "pe", "sr", "uy", "ve",
]

const NAMES := {
	"old": {
		"reino-portugal": ["Kingdom of Portugal (1830–1910)", "Reino de Portugal (1830–1910)"],
		"portugal-reino-unido-brasil": ["United Kingdom of Portugal, Brazil and the Algarves (1815–1822)", "Reino Unido de Portugal, Brasil e Algarves (1815–1822)"],
		"portugal-restauracao": ["Kingdom of Portugal (Restoration, John IV, 1640–1656)", "Reino de Portugal (Restauração, D. João IV, 1640–1656)"],
		"macau-governo": ["Macau (Government flag, semi-official, 1976–1999)", "Macau (bandeira do Governo, semioficial, 1976–1999)"],
		"rodesia": ["Rhodesia (1968–1979)", "Rodésia (1968–1979)"],
		"zaire": ["Zaire (1971–1997)", "Zaire (1971–1997)"],
		"polonia-1927": ["Poland (State flag, 1927–1980)", "Polónia (bandeira de Estado, 1927–1980)"],
		"lituania-rss": ["Lithuania (Lithuanian SSR, 1953–1988)", "Lituânia (RSS da Lituânia, 1953–1988)"],
		"urss": ["Soviet Union (1955–1991)", "União Soviética (1955–1991)"],
		"alemanha-leste": ["East Germany / GDR (1959–1990)", "Alemanha de Leste / RDA (1959–1990)"],
		"jugoslavia": ["Yugoslavia (1945–1992)", "Jugoslávia (1945–1992)"],
		"checoslovaquia": ["Czechoslovakia (1920–1992)", "Checoslováquia (1920–1992)"],
		"vietname-sul": ["South Vietnam (1955–1975)", "Vietname do Sul (1955–1975)"],
		"confederados-eua": ["Confederate States of America (1861–1863)", "Estados Confederados da América (1861–1863)"],
		"manchukuo": ["Manchukuo (1932–1945)", "Manchukuo (1932–1945)"],
		"italia-reino": ["Kingdom of Italy (1861–1946)", "Reino de Itália (1861–1946)"],
		"italia-napoleonica": ["Napoleonic Kingdom of Italy (1805–1814)", "Reino de Itália Napoleónico (1805–1814)"],
		"alemanha-imperial": ["German Empire (1871–1918)", "Império Alemão (1871–1918)"],
		"egito-reino": ["Kingdom of Egypt (1922–1953)", "Reino do Egito (1922–1953)"],
		"transvaal": ["Transvaal / South African Republic (1857–1902)", "Transvaal / República Sul-Africana (1857–1902)"],
		"brasil-imperio": ["Empire of Brazil (1822–1889)", "Império do Brasil (1822–1889)"],
		"terra-nova": ["Newfoundland (1904–1949)", "Terra Nova (1904–1949)"],
		"imperio-romano": ["Roman Empire", "Império Romano"],
		"reino-de-franca": ["Kingdom of France (14th–16th century)", "Reino de França (séc. XIV–XVI)"],
		"dinastia-qing": ["China (Qing dynasty, 1889–1912)", "China (dinastia Qing, 1889–1912)"],
		"aragao": ["Kingdom of Aragon", "Reino de Aragão"],
		"veneza": ["Republic of Venice (697–1797)", "República de Veneza (697–1797)"],
		"grao-ducado-lituania": ["Grand Duchy of Lithuania (14th–16th century)", "Grão-Ducado da Lituânia (séc. XIV–XVI)"],
		"austria-hungria": ["Austria-Hungary (1867–1918)", "Áustria-Hungria (1867–1918)"],
		"prussia": ["Kingdom of Prussia (1803–1892)", "Reino da Prússia (1803–1892)"],
		"portugal-1095": ["County of Portugal (1095–1143)", "Condado Portucalense (1095–1143)"],
		"portugal-descobrimentos": ["Kingdom of Portugal (Age of Discovery, 1485–1521)", "Reino de Portugal (Era dos Descobrimentos, 1485–1521)"],
		"sacro-imperio-romano": ["Holy Roman Empire (1400–1806)", "Sacro Império Romano-Germânico (1400–1806)"],
		"ordem-teutonica": ["Teutonic Order (Monastic State, 13th–16th century)", "Ordem Teutónica (Estado Monástico, séc. XIII–XVI)"],
		"augsburgo": ["Augsburg (Bavaria, Germany)", "Augsburgo (Baviera, Alemanha)"],
		"duas-sicilias": ["Kingdom of the Two Sicilies (1816–1848)", "Reino das Duas Sicílias (1816–1848)"],
		"imperio-russo": ["Russian Empire (1858–1896)", "Império Russo (1858–1896)"],
		"imperio-otomano": ["Ottoman Empire (1844–1922)", "Império Otomano (1844–1922)"],
		"imperio-japones": ["Empire of Japan (war flag, 1868–1945)", "Império do Japão (bandeira de guerra, 1868–1945)"],
		"uniao-sul-africana": ["Union of South Africa (1928–1994)", "União Sul-Africana (1928–1994)"],
		"primeiro-imperio-mexicano": ["First Mexican Empire (1821–1823)", "Primeiro Império Mexicano (1821–1823)"],
		"gra-colombia": ["Gran Colombia (1821–1830)", "Grã-Colômbia (1821–1830)"],
		"polonia-lituania": ["Polish–Lithuanian Commonwealth (1569–1795)", "Confederação Polaco-Lituana (1569–1795)"],
		"eua-13-estrelas": ["United States (13 stars, 1777–1795)", "Estados Unidos (13 estrelas, 1777–1795)"],
		"eua-15-estrelas": ["United States (15 stars, 1795–1818)", "Estados Unidos (15 estrelas, 1795–1818)"],
		"eua-20-estrelas": ["United States (20 stars, 1818–1819)", "Estados Unidos (20 estrelas, 1818–1819)"],
		"eua-48-estrelas": ["United States (48 stars, 1912–1959)", "Estados Unidos (48 estrelas, 1912–1959)"],
		"canada-red-ensign": ["Canada (Red Ensign, 1921–1957)", "Canadá (Red Ensign, 1921–1957)"],
		"mexico-primeira-republica": ["Mexico (First Republic, 1823–1864)", "México (Primeira República, 1823–1864)"],
		"argentina-belgrano": ["Argentina (Belgrano's flag, 1812)", "Argentina (bandeira de Belgrano, 1812)"],
		"chile-patria-vieja": ["Chile (Patria Vieja, 1812–1814)", "Chile (Patria Vieja, 1812–1814)"],
		"peru-1820": ["Peru (1820)", "Peru (1820)"],
		"venezuela-1811": ["Venezuela (First Republic, 1811)", "Venezuela (Primeira República, 1811)"],
		"indias-orientais-holandesas": ["Dutch East Indies (Dutch East India Company, 17th–18th century)", "Índias Orientais Holandesas (Companhia das Índias, séc. XVII–XVIII)"],
		"cruz-de-borgonha": ["Spanish Empire (Cross of Burgundy)", "Império Espanhol (Cruz da Borgonha)"],
		"franca-bourbon": ["France (Royal Bourbon flag)", "França (bandeira real dos Bourbon)"],
		"reino-unido-1707": ["United Kingdom (Union Flag, 1707–1801)", "Reino Unido (bandeira da União, 1707–1801)"],
		"inglaterra-sao-jorge": ["England (St George's Cross)", "Inglaterra (Cruz de São Jorge)"],
		"reino-da-grecia": ["Kingdom of Greece (1863–1924 / 1935–1973)", "Reino da Grécia (1863–1924 / 1935–1973)"],
		"imperio-austriaco": ["Austrian Empire (1804–1867)", "Império Austríaco (1804–1867)"],
		"reino-da-hungria": ["Kingdom of Hungary (1915–1918 / 1919–1946)", "Reino da Hungria (1915–1918 / 1919–1946)"],
		"reino-da-romenia": ["Kingdom of Romania (1881–1947)", "Reino da Roménia (1881–1947)"],
		"reino-da-servia": ["Kingdom of Serbia (1882–1918)", "Reino da Sérvia (1882–1918)"],
		"reino-da-bulgaria": ["Kingdom of Bulgaria (1878–1944)", "Reino da Bulgária (1878–1944)"],
		"libia-jamahiriya": ["Libyan Arab Jamahiriya (1977–2011 flag)", "República Árabe da Líbia (bandeira de 1977–2011)"],
		"ducado-varsovia": ["Duchy of Warsaw (1807–1815)", "Ducado de Varsóvia (1807–1815)"],
		"westfalia": ["Kingdom of Westphalia (1807–1813)", "Reino da Vestefália (1807–1813)"],
		"danzig": ["Free City of Danzig (1920–1939)", "Cidade Livre de Danzig (1920–1939)"],
		"montenegro-reino": ["Kingdom of Montenegro (1905–1918)", "Reino do Montenegro (1905–1918)"],
		"estados-papais": ["Papal States (before 1808)", "Estados Pontifícios (antes de 1808)"],
		"sardenha-reino": ["Kingdom of Sardinia (House of Savoy)", "Reino da Sardenha (Casa de Sabóia)"],
		"grao-ducado-toscana": ["Grand Duchy of Tuscany (1840)", "Grão-Ducado da Toscana (1840)"],
		"protetorado-sarre": ["Saar Protectorate (1947–1956)", "Protetorado do Sarre (1947–1956)"],
		"estado-cretense": ["Cretan State (1898–1913)", "Estado Cretense (1898–1913)"],
		"noruega-suecia-uniao": ["Sweden–Norway (union flag, 1844–1905)", "União Suécia-Noruega (bandeira de união, 1844–1905)"],
		"paises-baixos-prinsenvlag": ["Seven United Provinces of the Netherlands (Prinsenvlag)", "Sete Províncias Unidas dos Países Baixos (Prinsenvlag)"],
		"baden-grao-ducado": ["Grand Duchy of Baden (1891–1918)", "Grão-Ducado de Baden (1891–1918)"],
		"frankfurt-cidade-livre": ["Free City of Frankfurt (1813–1866)", "Cidade Livre de Frankfurt (1813–1866)"],
		"oldenburg-grao-ducado": ["Grand Duchy of Oldenburg", "Grão-Ducado de Oldemburgo"],
		"iugoslavia-reino": ["Kingdom of Yugoslavia (1918–1941)", "Reino da Jugoslávia (1918–1941)"],
		"trieste-territorio": ["Free Territory of Trieste (1947–1954)", "Território Livre de Trieste (1947–1954)"],
		"parma-ducado": ["Duchy of Parma", "Ducado de Parma"],
		"modena-ducado": ["Duchy of Modena", "Ducado de Módena"],
		"galicia-lodomeria": ["Kingdom of Galicia and Lodomeria (1809–1849)", "Reino da Galícia e Lodoméria (1809–1849)"],
		"ragusa-republica": ["Republic of Ragusa / Dubrovnik (1358–1808)", "República de Ragusa / Dubrovnik (1358–1808)"],
		"etruria": ["Kingdom of Etruria (1801–1807)", "Reino da Etrúria (1801–1807)"],
		"lucca-ducado": ["Duchy of Lucca (1815–1847)", "Ducado de Lucca (1815–1847)"],
		"roma-republica-1798": ["Roman Republic (1798–1799)", "República Romana (1798–1799)"],
		"partenopeia": ["Parthenopean Republic (1799)", "República Partenopeia (1799)"],
		"septinsular": ["Septinsular Republic (Ionian Islands, 1800–1807)", "República das Sete Ilhas (Jónicas, 1800–1807)"],
		"ilhas-jonicas": ["United States of the Ionian Islands (British protectorate, 1815–1864)", "Estados Unidos das Ilhas Jónicas (protetorado britânico, 1815–1864)"],
		"berg-grao-ducado": ["Grand Duchy of Berg (1806–1808)", "Grão-Ducado de Berg (1806–1808)"],
		"oeste-florida": ["Republic of West Florida (1810)", "República da Florida Ocidental (1810)"],
		"rio-grande": ["Republic of Rio Grande (1840)", "República do Rio Grande (1840)"],
		"china-cinco-cores": ["China (Five-Colored Flag, 1912–1928)", "China (Bandeira das Cinco Cores, 1912–1928)"],
		"siao-elefante": ["Kingdom of Siam (1855–1916)", "Reino do Sião (1855–1916)"],
		"raj-britanico": ["British India / Raj (Governor-General's flag, 1885–1947)", "Índia Britânica / Raj (bandeira do Governador-Geral, 1885–1947)"],
		"siquim": ["Kingdom of Sikkim (1967–1975)", "Reino do Sikkim (1967–1975)"],
		"birmania-konbaung": ["Burma (Konbaung dynasty)", "Birmânia (Dinastia Konbaung)"],
		"formosa-republica": ["Republic of Formosa (1895)", "República de Formosa (1895)"],
		"iraque-reino": ["Kingdom of Iraq (1924–1959)", "Reino do Iraque (1924–1959)"],
		"iemen-mutawakkilita": ["Mutawakkilite Kingdom of Yemen", "Reino Mutawakkilita do Iémen"],
		"estado-livre-laranja": ["Orange Free State (1854–1902)", "Estado Livre de Orange (1854–1902)"],
		"biafra": ["Republic of Biafra (1967–1970)", "República do Biafra (1967–1970)"],
		"catanga": ["State of Katanga (1960–1963)", "Estado do Catanga (1960–1963)"],
		"afeganistao-1928": ["Kingdom of Afghanistan (1928)", "Reino do Afeganistão (1928)"],
		"congo-livre": ["Congo Free State / Belgian Congo (1885–1960)", "Estado Livre do Congo / Congo Belga (1885–1960)"],
		"hong-kong-britanico": ["British Hong Kong (1959–1997)", "Hong Kong Britânico (1959–1997)"],
		"costa-do-ouro": ["British Gold Coast (1877–1957)", "Costa do Ouro Britânica (1877–1957)"],
		"guiana-britanica": ["British Guiana (1919–1955)", "Guiana Britânica (1919–1955)"],
		"rodesia-do-sul": ["Southern Rhodesia (1924–1953, 1963–1964)", "Rodésia do Sul (1924–1953, 1963–1964)"],
		"chipre-britanico": ["British Cyprus (1922–1960)", "Chipre Britânico (1922–1960)"],
		"malta-1943": ["Malta (1943–1964 flag, with the George Cross)", "Malta (bandeira de 1943–1964, com a Cruz de Jorge)"],
		"mandato-britanico-palestina": ["British Mandate for Palestine (civil flag, 1927–1948)", "Mandato Britânico da Palestina (bandeira civil, 1927–1948)"],
		"catar-britanico": ["Qatar under British protection (pre-1932 flag)", "Catar sob proteção britânica (bandeira antes de 1932)"],
		"trucial-states": ["Trucial States / Dubai (union flag, 1968–1971)", "Estados da Trégua / Dubai (bandeira de união, 1968–1971)"],
		"argelia-francesa": ["French Algeria (naval ensign, 1848–1910)", "Argélia Francesa (pavilhão naval, 1848–1910)"],
		"marrocos-1666": ["Morocco under French protectorate (plain red flag, pre-1915)", "Marrocos sob protetorado francês (bandeira vermelha lisa, antes de 1915)"],
		"lubeque": ["Free City of Lübeck (19th-century flag)", "Cidade Livre de Lübeque (bandeira do séc. XIX)"],
		"polonia-congresso": ["Congress Poland (Poland under Russia, 1815–1830)", "Reino do Congresso (Polónia sob a Rússia, 1815–1830)"],
		"curlandia": ["Duchy of Courland and Semigallia (1561–1795)", "Ducado da Curlândia e Semigália (1561–1795)"],
		"bizancio-paleologo": ["Byzantine Empire (Palaiologos dynasty, 1259–1453)", "Império Bizantino (dinastia Paleólogo, 1259–1453)"],
		"cispadana": ["Cispadane Republic (1796–1797)", "República Cispadana (1796–1797)"],
		"principados-unidos": ["United Principalities of Moldavia and Wallachia (1859–1862)", "Principados Unidos da Moldávia e Valáquia (1859–1862)"],
		"hesse-grao-ducado": ["Grand Duchy of Hesse (1806–1918)", "Grão-Ducado de Hesse (1806–1918)"],
		"waldeck": ["Principality of Waldeck (before 1830)", "Principado de Waldeck (antes de 1830)"],
		"reuss": ["Principality of Reuss-Lobenstein (until 1848)", "Principado de Reuss-Lobenstein (até 1848)"],
		"lippe": ["Principality of Lippe (1815–1880)", "Principado de Lippe (1815–1880)"],
		"saxe-weimar": ["Grand Duchy of Saxe-Weimar-Eisenach (1813–1897)", "Grão-Ducado de Saxe-Weimar-Eisenach (1813–1897)"],
		"estado-livre-fiume": ["Free State of Fiume (1920–1924)", "Estado Livre de Fiume (1920–1924)"],
		"bielorrusia-nacional": ["Belarusian Democratic Republic (1918)", "República Democrática Bielorrussa (1918)"],
		"georgia-democratica": ["Democratic Republic of Georgia (1918–1921)", "República Democrática da Geórgia (1918–1921)"],
		"helvetica-republica": ["Helvetic Republic (1798–1803)", "República Helvética (1798–1803)"],
		"albania-reino": ["Kingdom of Albania, Zog I (1928–1934)", "Reino da Albânia, Zog I (1928–1934)"],
		"montenegro-principado": ["Principality of Montenegro (1852–1860)", "Principado do Montenegro (1852–1860)"],
		"transilvania": ["Transylvania (Principality)", "Transilvânia (Principado)"],
		"valaquia": ["Wallachia (Principality)", "Valáquia (Principado)"],
		"moldavia-principado": ["Moldavia (Principality)", "Moldávia (Principado)"],
		"rss-ucrania": ["Ukrainian SSR (1949–1991)", "RSS da Ucrânia (1949–1991)"],
		"rss-bielorrussia": ["Byelorussian SSR (1951–1991)", "RSS da Bielorrússia (1951–1991)"],
		"rss-cazaquistao": ["Kazakh SSR (1953–1991)", "RSS do Cazaquistão (1953–1991)"],
		"rss-usbequistao": ["Uzbek SSR (1952–1991)", "RSS do Usbequistão (1952–1991)"],
		"rss-turcomenistao": ["Turkmen SSR (1974–1991)", "RSS do Turquemenistão (1974–1991)"],
		"rss-azerbaijao": ["Azerbaijan SSR (1952–1991)", "RSS do Azerbaijão (1952–1991)"],
		"rss-armenia": ["Armenian SSR (1952–1990)", "RSS da Arménia (1952–1990)"],
		"rss-georgia": ["Georgian SSR (1951–1990)", "RSS da Geórgia (1951–1990)"],
		"rss-letonia": ["Latvian SSR (1953–1990)", "RSS da Letónia (1953–1990)"],
		"rss-estonia": ["Estonian SSR (1953–1990)", "RSS da Estónia (1953–1990)"],
		"rss-moldavia": ["Moldavian SSR (1952–1990)", "RSS da Moldávia (1952–1990)"],
		"rss-tajiquistao": ["Tajik SSR (1953–1991)", "RSS do Tajiquistão (1953–1991)"],
		"rss-quirguizistao": ["Kirghiz SSR (1952–1991)", "RSS do Quirguizistão (1952–1991)"],
		"rss-macedonia": ["Socialist Republic of Macedonia, within Yugoslavia (1946–1991)", "República Socialista da Macedónia, na Jugoslávia (1946–1991)"],
		"rss-eslovenia": ["Socialist Republic of Slovenia, within Yugoslavia (1945–1991)", "República Socialista da Eslovénia, na Jugoslávia (1945–1991)"],
		"rss-croacia": ["Socialist Republic of Croatia, within Yugoslavia (1947–1990)", "República Socialista da Croácia, na Jugoslávia (1947–1990)"],
		"rss-bosnia": ["Socialist Republic of Bosnia and Herzegovina, within Yugoslavia (1946–1992)", "República Socialista da Bósnia e Herzegovina, na Jugoslávia (1946–1992)"],
		"rss-servia": ["Socialist Republic of Serbia, within Yugoslavia (1947–1992)", "República Socialista da Sérvia, na Jugoslávia (1947–1992)"],
		"brasil-imperio-1822": ["Empire of Brazil, 1st flag, 19 stars (1822–1853)", "Império do Brasil, 1ª bandeira, 19 estrelas (1822–1853)"],
		"rio-grandense-piratini": ["Riograndense Republic / Piratini (1836–1845)", "República Rio-Grandense / Piratini (1836–1845)"],
		"republica-juliana": ["Julian Republic / Catarinense (1839)", "República Juliana / Catarinense (1839)"],
		"yucatao": ["Republic of Yucatán (1841–1848)", "República do Iucatão (1841–1848)"],
		"centro-americana": ["Federal Republic of Central America (1823–1841)", "Repúblicas Federadas da América Central (1823–1841)"],
		"peru-bolivia": ["Peru–Bolivian Confederation (1836–1839)", "Confederação Peru-Boliviana (1836–1839)"],
		"haiti-1803": ["Haiti (independence flag, 1803–1804)", "Haiti (bandeira da independência, 1803–1804)"],
		"mengjiang": ["Mengjiang (1936–1945)", "Mengcheguo / Mengjiang (1936–1945)"],
		"turquestao-oriental": ["2nd East Turkestan Republic (1944–1949)", "2ª República do Turquestão Oriental (1944–1949)"],
		"sarawak": ["Kingdom of Sarawak (1870–1946)", "Reino de Sarawak (1870–1946)"],
		"zanzibar-sultanato": ["Sultanate of Zanzibar (until 1964)", "Sultanato de Zanzibar (até 1964)"],
		"hatay": ["Republic of Hatay (1938–1939)", "República de Hatay (1938–1939)"],
		"hejaz": ["Kingdom of Hejaz (1917–1925)", "Reino do Hejaz (1917–1925)"],
		"arabia-sul-federacao": ["Federation of South Arabia (1962–1967)", "Federação da Arábia do Sul (1962–1967)"],
		"iemen-sul": ["People's Republic of South Yemen (1967–1990)", "República Popular do Iémen do Sul (1967–1990)"],
		"malaia-britanica": ["Federated Malay States (1896–1950)", "Estados Malaios Federados (1896–1950)"],
		"indochina-francesa": ["Annam (French protectorate, Indochina, colonial flag)", "Anam (protetorado francês, Indochina, bandeira colonial)"],
		"ceilao-colonia": ["British Ceylon (1875–1948)", "Ceilão Britânico (1875–1948)"],
		"birmania-britanica": ["British Burma (1939–1941, 1945–1948)", "Birmânia Britânica (1939–1941, 1945–1948)"],
		"birmania-uniao-1948": ["Union of Burma (1948–1974)", "União da Birmânia (1948–1974)"],
		"birmania-1974": ["Socialist Republic of the Union of Burma (1974–2010)", "República Socialista da União da Birmânia (1974–2010)"],
		"afeganistao-1930": ["Kingdom of Afghanistan (Zahir Shah, 1931–1973)", "Reino do Afeganistão (Zahir Shah, 1931–1973)"],
		"afeganistao-1980": ["Democratic Republic of Afghanistan (1980–1987)", "República Democrática do Afeganistão (1980–1987)"],
		"republica-arabe-unida": ["United Arab Republic (Egypt and Syria, 1958–1971)", "República Árabe Unida (Egito e Síria, 1958–1971)"],
		"laos-reino": ["Kingdom of Laos (1952–1975)", "Reino do Laos (1952–1975)"],
		"khmer-republica": ["Khmer Republic (1970–1975)", "República Khmer (1970–1975)"],
		"mongolia-rpm": ["Mongolian People's Republic (1945–1992)", "República Popular da Mongólia (1945–1992)"],
		"borneo-norte-britanico": ["British North Borneo (1902–1946)", "Borneu do Norte Britânico (1902–1946)"],
		"etiopia-imperio": ["Ethiopian Empire (1897–1974)", "Império da Etiópia (1897–1974)"],
		"libano-mandato": ["Lebanon under French mandate (1920–1943)", "Líbano sob mandato francês (1920–1943)"],
		"aden-colonia": ["Colony of Aden (1937–1963)", "Colónia de Áden (1937–1963)"],
		"sudao-anglo-egipcio": ["Anglo-Egyptian Sudan (1899–1956)", "Sudão Anglo-Egípcio (1899–1956)"],
		"somalilandia-britanica": ["British Somaliland (1903–1950)", "Somalilândia Britânica (1903–1950)"],
		"rodesia-do-norte": ["Northern Rhodesia (1939–1964)", "Rodésia do Norte (1939–1964)"],
		"niassalandia": ["Nyasaland (1925–1964)", "Niassalândia (1925–1964)"],
		"rodesia-niassalandia": ["Federation of Rhodesia and Nyasaland (1953–1963)", "Federação da Rodésia e Niassalândia (1953–1963)"],
		"quenia-colonia": ["British East Africa Protectorate (1895–1920)", "Protetorado da África Oriental Britânica (1895–1920)"],
		"uganda-protetorado": ["Uganda Protectorate (1894–1962)", "Protetorado do Uganda (1894–1962)"],
		"tanganhica": ["Tanganyika (1961–1964)", "Tanganhica (1961–1964)"],
		"africa-equatorial-francesa": ["French Equatorial Africa (1910–1958)", "África Equatorial Francesa (1910–1958)"],
		"natal-colonia": ["Colony of Natal (1875–1910)", "Colónia do Natal (1875–1910)"],
		"congo-republica-popular": ["People's Republic of the Congo (1970–1991)", "República Popular do Congo (1970–1991)"],
		"zimbabwe-rodesia": ["Zimbabwe Rhodesia (1979)", "Zimbabwe-Rodésia (1979)"],
	},
	"classic": {
		"za": ["South Africa", "África do Sul"],
		"ao": ["Angola", "Angola"],
		"dz": ["Algeria", "Argélia"],
		"bj": ["Benin", "Benim"],
		"bw": ["Botswana", "Botsuana"],
		"bf": ["Burkina Faso", "Burquina Faso"],
		"bi": ["Burundi", "Burundi"],
		"cv": ["Cape Verde", "Cabo Verde"],
		"cm": ["Cameroon", "Camarões"],
		"td": ["Chad", "Chade"],
		"km": ["Comoros", "Comores"],
		"cg": ["Republic of the Congo", "Congo"],
		"cd": ["Democratic Republic of the Congo", "República Democrática do Congo"],
		"ci": ["Ivory Coast", "Costa do Marfim"],
		"eg": ["Egypt", "Egito"],
		"er": ["Eritrea", "Eritreia"],
		"sz": ["Eswatini", "Essuatíni"],
		"et": ["Ethiopia", "Etiópia"],
		"ga": ["Gabon", "Gabão"],
		"gm": ["Gambia", "Gâmbia"],
		"gh": ["Ghana", "Gana"],
		"gn": ["Guinea", "Guiné"],
		"gw": ["Guinea-Bissau", "Guiné-Bissau"],
		"gq": ["Equatorial Guinea", "Guiné Equatorial"],
		"dj": ["Djibouti", "Jibuti"],
		"ls": ["Lesotho", "Lesoto"],
		"lr": ["Liberia", "Libéria"],
		"ly": ["Libya", "Líbia"],
		"mg": ["Madagascar", "Madagáscar"],
		"mw": ["Malawi", "Malawi"],
		"ml": ["Mali", "Mali"],
		"ma": ["Morocco", "Marrocos"],
		"mu": ["Mauritius", "Maurícia"],
		"mr": ["Mauritania", "Mauritânia"],
		"mz": ["Mozambique", "Moçambique"],
		"na": ["Namibia", "Namíbia"],
		"ne": ["Niger", "Níger"],
		"ng": ["Nigeria", "Nigéria"],
		"ke": ["Kenya", "Quénia"],
		"cf": ["Central African Republic", "República Centro-Africana"],
		"rw": ["Rwanda", "Ruanda"],
		"st": ["São Tomé and Príncipe", "São Tomé e Príncipe"],
		"sn": ["Senegal", "Senegal"],
		"sl": ["Sierra Leone", "Serra Leoa"],
		"sc": ["Seychelles", "Seicheles"],
		"so": ["Somalia", "Somália"],
		"sd": ["Sudan", "Sudão"],
		"ss": ["South Sudan", "Sudão do Sul"],
		"tz": ["Tanzania", "Tanzânia"],
		"tg": ["Togo", "Togo"],
		"tn": ["Tunisia", "Tunísia"],
		"ug": ["Uganda", "Uganda"],
		"zm": ["Zambia", "Zâmbia"],
		"zw": ["Zimbabwe", "Zimbabué"],
		"af": ["Afghanistan", "Afeganistão"],
		"sa": ["Saudi Arabia", "Arábia Saudita"],
		"am": ["Armenia", "Arménia"],
		"az": ["Azerbaijan", "Azerbaijão"],
		"bd": ["Bangladesh", "Bangladeche"],
		"bh": ["Bahrain", "Barém"],
		"bt": ["Bhutan", "Butão"],
		"bn": ["Brunei", "Brunei"],
		"kh": ["Cambodia", "Camboja"],
		"qa": ["Qatar", "Catar"],
		"kz": ["Kazakhstan", "Cazaquistão"],
		"cn": ["China", "China"],
		"cy": ["Cyprus", "Chipre"],
		"kp": ["North Korea", "Coreia do Norte"],
		"kr": ["South Korea", "Coreia do Sul"],
		"ae": ["United Arab Emirates", "Emirados Árabes Unidos"],
		"ph": ["Philippines", "Filipinas"],
		"ge": ["Georgia", "Geórgia"],
		"in": ["India", "Índia"],
		"id": ["Indonesia", "Indonésia"],
		"ir": ["Iran", "Irão"],
		"iq": ["Iraq", "Iraque"],
		"il": ["Israel", "Israel"],
		"jp": ["Japan", "Japão"],
		"jo": ["Jordan", "Jordânia"],
		"kw": ["Kuwait", "Kuwait"],
		"la": ["Laos", "Laos"],
		"lb": ["Lebanon", "Líbano"],
		"my": ["Malaysia", "Malásia"],
		"mv": ["Maldives", "Maldivas"],
		"mn": ["Mongolia", "Mongólia"],
		"mm": ["Myanmar", "Myanmar"],
		"np": ["Nepal", "Nepal"],
		"om": ["Oman", "Omã"],
		"pk": ["Pakistan", "Paquistão"],
		"kg": ["Kyrgyzstan", "Quirguistão"],
		"sg": ["Singapore", "Singapura"],
		"sy": ["Syria", "Síria"],
		"lk": ["Sri Lanka", "Sri Lanka"],
		"th": ["Thailand", "Tailândia"],
		"tj": ["Tajikistan", "Tajiquistão"],
		"tl": ["Timor-Leste", "Timor-Leste"],
		"tm": ["Turkmenistan", "Turquemenistão"],
		"tr": ["Turkey", "Turquia"],
		"uz": ["Uzbekistan", "Usbequistão"],
		"vn": ["Vietnam", "Vietname"],
		"ye": ["Yemen", "Iémen"],
		"ps": ["Palestine", "Palestina"],
		"de": ["Germany", "Alemanha"],
		"al": ["Albania", "Albânia"],
		"ad": ["Andorra", "Andorra"],
		"at": ["Austria", "Áustria"],
		"be": ["Belgium", "Bélgica"],
		"by": ["Belarus", "Bielorrússia"],
		"ba": ["Bosnia and Herzegovina", "Bósnia e Herzegovina"],
		"bg": ["Bulgaria", "Bulgária"],
		"hr": ["Croatia", "Croácia"],
		"dk": ["Denmark", "Dinamarca"],
		"sk": ["Slovakia", "Eslováquia"],
		"si": ["Slovenia", "Eslovénia"],
		"es": ["Spain", "Espanha"],
		"ee": ["Estonia", "Estónia"],
		"fi": ["Finland", "Finlândia"],
		"fr": ["France", "França"],
		"gr": ["Greece", "Grécia"],
		"hu": ["Hungary", "Hungria"],
		"ie": ["Ireland", "Irlanda"],
		"is": ["Iceland", "Islândia"],
		"it": ["Italy", "Itália"],
		"lv": ["Latvia", "Letónia"],
		"li": ["Liechtenstein", "Listenstaine"],
		"lt": ["Lithuania", "Lituânia"],
		"lu": ["Luxembourg", "Luxemburgo"],
		"mk": ["North Macedonia", "Macedónia do Norte"],
		"mt": ["Malta", "Malta"],
		"md": ["Moldova", "Moldávia"],
		"mc": ["Monaco", "Mónaco"],
		"me": ["Montenegro", "Montenegro"],
		"no": ["Norway", "Noruega"],
		"nl": ["Netherlands", "Países Baixos"],
		"pl": ["Poland", "Polónia"],
		"pt": ["Portugal", "Portugal"],
		"gb": ["United Kingdom", "Reino Unido"],
		"cz": ["Czechia", "República Checa"],
		"ro": ["Romania", "Roménia"],
		"ru": ["Russia", "Rússia"],
		"sm": ["San Marino", "São Marino"],
		"rs": ["Serbia", "Sérvia"],
		"se": ["Sweden", "Suécia"],
		"ch": ["Switzerland", "Suíça"],
		"ua": ["Ukraine", "Ucrânia"],
		"va": ["Vatican City", "Vaticano"],
		"au": ["Australia", "Austrália"],
		"fj": ["Fiji", "Fiji"],
		"mh": ["Marshall Islands", "Ilhas Marshall"],
		"sb": ["Solomon Islands", "Ilhas Salomão"],
		"ki": ["Kiribati", "Kiribati"],
		"fm": ["Micronesia", "Micronésia"],
		"nr": ["Nauru", "Nauru"],
		"nz": ["New Zealand", "Nova Zelândia"],
		"pw": ["Palau", "Palau"],
		"pg": ["Papua New Guinea", "Papua-Nova Guiné"],
		"ws": ["Samoa", "Samoa"],
		"to": ["Tonga", "Tonga"],
		"tv": ["Tuvalu", "Tuvalu"],
		"vu": ["Vanuatu", "Vanuatu"],
		"ag": ["Antigua and Barbuda", "Antígua e Barbuda"],
		"bs": ["Bahamas", "Bahamas"],
		"bb": ["Barbados", "Barbados"],
		"bz": ["Belize", "Belize"],
		"ca": ["Canada", "Canadá"],
		"cr": ["Costa Rica", "Costa Rica"],
		"cu": ["Cuba", "Cuba"],
		"dm": ["Dominica", "Dominica"],
		"do": ["Dominican Republic", "República Dominicana"],
		"sv": ["El Salvador", "El Salvador"],
		"us": ["United States", "Estados Unidos"],
		"gd": ["Grenada", "Granada"],
		"gt": ["Guatemala", "Guatemala"],
		"ht": ["Haiti", "Haiti"],
		"hn": ["Honduras", "Honduras"],
		"jm": ["Jamaica", "Jamaica"],
		"mx": ["Mexico", "México"],
		"ni": ["Nicaragua", "Nicarágua"],
		"pa": ["Panama", "Panamá"],
		"kn": ["Saint Kitts and Nevis", "São Cristóvão e Neves"],
		"lc": ["Saint Lucia", "Santa Lúcia"],
		"vc": ["Saint Vincent and the Grenadines", "São Vicente e Granadinas"],
		"tt": ["Trinidad and Tobago", "Trindade e Tobago"],
		"ar": ["Argentina", "Argentina"],
		"bo": ["Bolivia", "Bolívia"],
		"br": ["Brazil", "Brasil"],
		"cl": ["Chile", "Chile"],
		"co": ["Colombia", "Colômbia"],
		"ec": ["Ecuador", "Equador"],
		"gy": ["Guyana", "Guiana"],
		"py": ["Paraguay", "Paraguai"],
		"pe": ["Peru", "Peru"],
		"sr": ["Suriname", "Suriname"],
		"uy": ["Uruguay", "Uruguai"],
		"ve": ["Venezuela", "Venezuela"],
	},
}
