extends RefCounted
## LEVEL 01 — THE DROP (story.md). Night. A Black Division helicopter flies Mercer's team toward the
## Dead Sector along a burning highway and is shot down outside the quarantine perimeter. With the
## rifle and pistol he started with, Mercer fights rogue sector security up the highway to the
## quarantine checkpoint, where the soldiers have been dead for weeks. Gunfire inside; the gates open;
## something runs through. Nobody gets a good look at it.

const DATA := {
	"id": "m01",
	"title": "m01_title",
	"location": "m01_location",
	"briefing": "m01_brief",
	"loadout": {"primary": "ar7", "secondary": "m25", "grenades": ["he"], "armor": 50.0, "helmet": true},
	"intro": "drop",
	"cines": {
		"drop": {
			"shots": [
				{"from": ["h0", 34, Vector3(0, 0, 30)], "to": ["h0", 28, Vector3(0, 0, -30)], "look": ["mid", 2], "look_to": ["gate", 4], "t": 14.0, "fov": 62.0,
					"say": [["hale", "m01_c1"], ["pilot", "m01_c2"], ["reyes", "m01_c3"], ["volkov", "m01_c4"]]},
				{"from": ["h0", 28, Vector3(0, 0, -30)], "to": ["h0", 12, Vector3(8, 0, -8)], "look": ["gate", 0], "look_to": ["h0", 0, Vector3(0, 0, -6)], "t": 3.2, "fov": 70.0,
					"roll": 2.4, "shake": 1.0, "sound": "bomb_explode", "say": [["pilot", "m01_c5", 2.5]]},
				{"from": ["h0", 1.0], "look": ["h0", 1.0, Vector3(0, 0, -5)], "t": 3.0, "fade": 1.0, "title": ["m01_title", "m01_location"]},
			],
			"then": [["sound", "ring"]],
		},
	},
	"areas": [
		{
			"theme": "night",
			"wall": "concrete", "wall_tint": Color(0.85, 0.85, 0.85), "floor": "asphalt", "paved": "dirt",
			"crate": "wood", "low": "concrete", "pillar": "concrete", "roof": "concrete", "wall_height": 6.0,
			"auto_lamps": false, "ambience": "wind",
			"legend": {
				"P": {"player": true},
				"R": {"ally": "reyes"}, "v": {"ally": "volkov"},
				"k": {"solid": "wall", "tex": "metal", "tint": Color(0.36, 0.42, 0.3), "height": 5.4},
				"B": {"solid": "wall", "tex": "brick"},
				"i": {"roof": 3.6, "floor": "tiles"},
				"m": {"roof": 3.6, "floor": "tiles", "item": "medkit"},
				"I": {"roof": 3.6, "floor": "tiles", "item": "intel", "id": "m01_i1"},
				"J": {"roof": 3.6, "floor": "tiles", "item": "intel", "id": "m01_i2"},
				"b": {"roof": 3.6, "floor": "tiles", "spawn": "w2"},
				"Q": {"item": "intel", "id": "m01_i3"},
				"n": {"item": "ammo"}, "A": {"item": "armor"},
				"S": {"prop": "sandbags", "block": 1.1},
				"V": {"prop": "car", "block": 1.5, "jitter": 0.3},
				"W": {"prop": "wreck", "block": 1.5, "jitter": 0.4},
				"T": {"prop": "truck", "block": 3.0},
				"H": {"prop": "heli_wreck", "block": 3.0, "turn": 20.0},
				"f": {"hazard": "fire"},
				"L": {"lamp": "street", "face": "s"},
				"x": {"corpse": "army"},
				"D": {"door": "gate1", "kind": "gate", "locked": true, "height": 4.2},
				"G": {"mark": "gate"}, "M": {"mark": "mid"}, "E": {"mark": "inside"}, "Z": {"mark": "away"}, "h": {"mark": "h0"},
				"1": {"trigger": "t_road"}, "2": {"trigger": "t_mid"}, "3": {"trigger": "t_check"}, "4": {"trigger": "t_station"},
				"a": {"spawn": "w1"},
				"r": {"enemy": "rogue", "mode": "guard", "group": "block"},
				"p": {"enemy": "rogue", "mode": "patrol", "group": "block"},
				"s": {"enemy": "sniper", "mode": "hold", "group": "block"},
				"u": {"enemy": "rogue", "mode": "patrol", "group": "check"},
			},
			"events": [
				{"id": "wake", "when": ["start"], "do": [
					["say", "reyes", "m01_l1"], ["say", "volkov", "m01_l2"], ["say", "reyes", "m01_l3"],
					["obj", "m01_o1", "", "w1"]]},
				{"id": "ambush", "when": ["after", "wake", 9.0], "do": [
					["spawn", "w1", "rogue", 5, "hunt", "w1"], ["say", "volkov", "m01_l4"]]},
				{"id": "ambush_done", "when": ["dead", "w1"], "do": [
					["say", "reyes", "m01_l5"], ["say", "hale", "m01_l6"], ["say", "hale", "m01_l7"],
					["obj", "m01_o2", "mid"], ["checkpoint"]]},
				{"id": "station", "when": ["enter", "t_station"], "do": [
					["say", "reyes", "m01_l8"], ["spawn", "w2", "rogue", 2, "hunt", "w2"]]},
				{"id": "block_seen", "when": ["enter", "t_mid"], "do": [["say", "volkov", "m01_l9"]]},
				{"id": "block_done", "when": ["dead", "block"], "do": [
					["say", "reyes", "m01_l10"], ["obj", "m01_o3", "gate"], ["checkpoint"]]},
				{"id": "check", "when": ["near", "gate", 17.0], "do": [
					["say", "volkov", "m01_l11"], ["say", "reyes", "m01_l12"], ["say", "hale", "m01_l13"],
					["obj", "m01_o4", "gate", "check"]]},
				{"id": "check_clear", "when": ["all", [["dead", "check"], ["near", "gate", 17.0]]], "do": [
					["checkpoint"], ["say", "volkov", "m01_l14"]]},
				{"id": "gunfire", "when": ["all", [["dead", "check"], ["near", "gate", 9.0]]], "do": [
					["sound", "ak", "inside", 4.0], ["say", "reyes", "m01_l15"]]},
				{"id": "gunfire2", "when": ["after", "gunfire", 1.2], "do": [["sound", "rifle", "inside", 4.0], ["shake", 0.2]]},
				{"id": "open", "when": ["after", "gunfire", 3.5], "do": [["open", "gate1"], ["alarm", true]]},
				{"id": "runner", "when": ["after", "open", 1.2], "do": [["glimpse", "inside", "away"], ["say", "volkov", "m01_l16"]]},
				{"id": "after", "when": ["after", "runner", 3.0], "do": [
					["say", "reyes", "m01_l17"], ["say", "hale", "m01_l18"]]},
				{"id": "end", "when": ["after", "after", 11.0], "do": [["complete"]]},
			],
			"map": [
				"############################################",
				"############################################",
				"####,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,####",
				"####,,E,,,,,TTT,,,,,,f,,,,,,,,,,ff,,,,,,####",
				"####,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,####",
				"####,,x,,,,,,,,,,,,,,,,,,,,,,,,,,,x,,,,,####",
				"kkkkkkkkkkkkkkkkkkkkDDDDkkkkkkkkkkkkkkkkkkkk",
				"##,,,,,,,,,,,,,,,,,,,,G,,,,,,,,,,,,,,,,,,,##",
				"##,,SSS,,,,,,x,,,,,,,,,,,,,,,,,x,,,,,SSS,,##",
				"##,,,,,,,,,,,,,,,,L,,,,,,L,,,,,,,,,,,,,,,,##",
				"##,,,,BBBBBB,,,,,,,,,,,,,,,,,,,,TTT,,,,,,,##",
				"##,,,,BiiiiB,,x,,,,,,,,,,,,x,,,,,,,,,,u,,,##",
				"Z,,,,,BiJimB,,,,,,,,-----,,,,,,,,,,,,,,,,,##",
				"##,,,,BBiBBB,,,,u,,,,,,,,,,,u,,,,,,,,,,,,,##",
				"##,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,##",
				"##,,cc,,,,,,,,33333333333333333,,,,,,cc,,,##",
				"####,,,,,,.....................,,,,,,,,,####",
				"####,,,,,,..........VV...........,,,,,,,####",
				"####,,,-,,.........................,,,,,####",
				"####,,,,,,.....WW.............VV.....,,,####",
				"####,,,,,,.......f.................,,,,#####",
				"####,,,,,,.....................TTT...,,,####",
				"####,n,,,,...VV..........r...........,,,####",
				"####,,,,,,................................##",
				"####,,,,,,.....-----.......-----.....,,,####",
				"####,,,,,,.....S.p...........p..S....,,,####",
				"####,,,,,,...........TTTr........s...,,,####",
				"####,,,,,,.....r........r............,,,####",
				"####,,,,,,.....-----.......-----.....,,,####",
				"####,,,,,,..............M.............,,####",
				"BBBBBBBBB,.........22222222222.......,,,####",
				"BiiiiiiiB,...VV.....................,,,,####",
				"BiiiiiiiB,.................WW........,,,####",
				"BiIiiiiii4,,.................f.......,,,####",
				"Biibbiiii4,,......VV.................,,,####",
				"BiiiiimiB,....................VV.....,,,####",
				"BBBBiBBBB,...........................,,,####",
				"####,,,,,,.....VV....................,,,####",
				"####,,,,,,.....................V.....,,,####",
				"####,,,,,,.....................V.....,Q,####",
				"####,,,,,,..WW.......................,,,####",
				"####,,,,,,...f.......................,,,####",
				"####,,,,,,..........11111111111......,,,####",
				"####,,,,,,..........a..a..a..a.......,,,####",
				"####,,,,,,...........................,,,####",
				"####,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,####",
				"####,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,####",
				"####,,,,,,,,,f,,,,,,,,,,,,,,,,f,,,,,,,,,####",
				"####,,,,,,,,,,,,,HHHHH,,,,,,,,,,,,,,,,,,####",
				"####,,,,,c,,,,,,,HHHHH,,,f,,,,,,,,c,,,,,####",
				"####,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,####",
				"####,,,A,,,,,,,,,R,,P,,v,,,,,,,,,,,,n,,,####",
				"####,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,####",
				"####,,,,,,,,,,,,,,h,,,,,,,,,,,,,,,,,,,,,####",
				"############################################",
				"############################################",
			],
		},
	],
}
