extends RefCounted
## Every text in the game, in each language. The game shows them with tr("key").
## Values follow the order of LANGUAGES.

const LANGUAGES := [["en", "English"], ["pt", "Português"], ["pt_BR", "Português (Brasil)"], ["es", "Español"], ["fr", "Français"],
		["de", "Deutsch"], ["it", "Italiano"], ["nl", "Nederlands"], ["pl", "Polski"], ["sv", "Svenska"]]

const TEXT := {
	# Menu.
	"title": ["24 Game Pro", "Jogo do 24 Pro", "Jogo do 24 Pro", "24 Game Pro", "24 Game Pro", "24 Game Pro", "24 Game Pro", "24 Game Pro",
			"24 Game Pro", "24 Game Pro"],
	"instructions": ["Combine the four numbers using +, −, × and ÷ until only one is left. If it is 24, you win!",
			"Combina os quatro números com +, −, × e ÷ até restar apenas um. Se for 24, ganhaste!",
			"Combine os quatro números com +, −, × e ÷ até sobrar apenas um. Se for 24, você ganhou!",
			"Combina los cuatro números con +, −, × y ÷ hasta que quede solo uno. ¡Si es 24, ganas!",
			"Combine les quatre nombres avec +, −, × et ÷ jusqu'à ce qu'il n'en reste qu'un. S'il vaut 24, tu gagnes !",
			"Kombiniere die vier Zahlen mit +, −, × und ÷, bis nur noch eine übrig ist. Ist sie 24, hast du gewonnen!",
			"Combina i quattro numeri con +, −, × e ÷ finché ne resta solo uno. Se è 24, hai vinto!",
			"Combineer de vier getallen met +, −, × en ÷ tot er nog maar één over is. Is het 24, dan win je!",
			"Łącz cztery liczby za pomocą +, −, × i ÷, aż zostanie tylko jedna. Jeśli to 24, wygrywasz!",
			"Kombinera de fyra talen med +, −, × och ÷ tills bara ett är kvar. Blir det 24 vinner du!"],
	"title_name": ["24 Game", "Jogo do 24", "Jogo do 24", "24 Game", "24 Game", "24 Game", "24 Game", "24 Game", "24 Game", "24 Game"],  # the title without "Pro", for the logo
	"mode_classic": ["Classic", "Clássico", "Clássico", "Clásico", "Classique", "Klassisch", "Classica", "Klassiek", "Klasyczny", "Klassiskt"],
	"mode_double": ["Double Cards", "Cartas Duplas", "Cartas Duplas", "Cartas Dobles", "Cartes Doubles", "Doppelkarten", "Carte Doppie",
			"Dubbele Kaarten", "Podwójne Karty", "Dubbelkort"],
	"instructions_double": ["Double Cards: combine all six numbers with +, −, × and ÷ until only one is left. If it is 24, you win!",
			"Cartas Duplas: combina os seis números com +, −, × e ÷ até restar apenas um. Se for 24, ganhaste!",
			"Cartas Duplas: combine os seis números com +, −, × e ÷ até sobrar apenas um. Se for 24, você ganhou!",
			"Cartas Dobles: combina los seis números con +, −, × y ÷ hasta que quede solo uno. ¡Si es 24, ganas!",
			"Cartes Doubles : combine les six nombres avec +, −, × et ÷ jusqu'à ce qu'il n'en reste qu'un. S'il vaut 24, tu gagnes !",
			"Doppelkarten: Kombiniere alle sechs Zahlen mit +, −, × und ÷, bis nur noch eine übrig ist. Ist sie 24, hast du gewonnen!",
			"Carte Doppie: combina i sei numeri con +, −, × e ÷ finché ne resta solo uno. Se è 24, hai vinto!",
			"Dubbele Kaarten: combineer alle zes getallen met +, −, × en ÷ tot er nog maar één over is. Is het 24, dan win je!",
			"Podwójne Karty: łącz wszystkie sześć liczb za pomocą +, −, × i ÷, aż zostanie tylko jedna. Jeśli to 24, wygrywasz!",
			"Dubbelkort: kombinera alla sex tal med +, −, × och ÷ tills bara ett är kvar. Blir det 24 vinner du!"],
	"choose_difficulty": ["Choose difficulty", "Escolhe a dificuldade", "Escolha a dificuldade", "Elige la dificultad",
			"Choisis la difficulté", "Schwierigkeit wählen", "Scegli la difficoltà", "Kies de moeilijkheid", "Wybierz poziom trudności",
			"Välj svårighetsgrad"],
	"level_easy": ["Easy", "Fácil", "Fácil", "Fácil", "Facile", "Leicht", "Facile", "Makkelijk", "Łatwy", "Lätt"],
	"level_medium": ["Medium", "Médio", "Médio", "Medio", "Moyen", "Mittel", "Medio", "Gemiddeld", "Średni", "Medel"],
	"level_hard": ["Hard", "Difícil", "Difícil", "Difícil", "Difficile", "Schwer", "Difficile", "Moeilijk", "Trudny", "Svår"],
	"level_very_hard": ["Very Hard", "Muito Difícil", "Muito Difícil", "Muy Difícil", "Très Difficile", "Sehr Schwer", "Molto Difficile",
			"Zeer Moeilijk", "Bardzo Trudny", "Mycket Svår"],
	"settings": ["Settings", "Definições", "Configurações", "Ajustes", "Paramètres", "Einstellungen", "Impostazioni", "Instellingen",
			"Ustawienia", "Inställningar"],
	"language": ["Language", "Idioma", "Idioma", "Idioma", "Langue", "Sprache", "Lingua", "Taal", "Język", "Språk"],
	"sound": ["Sound effects", "Efeitos sonoros", "Efeitos sonoros", "Efectos de sonido", "Effets sonores", "Soundeffekte",
			"Effetti sonori", "Geluidseffecten", "Efekty dźwiękowe", "Ljudeffekter"],
	"sound_desc": ["Clicks, moves and the win jingle.", "Cliques, jogadas e a música de vitória.",
			"Cliques, jogadas e a música de vitória.", "Clics, jugadas y la melodía de victoria.",
			"Clics, coups et la musique de victoire.", "Klicks, Züge und die Siegesmelodie.", "Clic, mosse e la musica di vittoria.",
			"Klikken, zetten en het overwinningsdeuntje.", "Kliknięcia, ruchy i melodia zwycięstwa.", "Klick, drag och segermelodin."],
	"volume": ["Volume", "Volume", "Volume", "Volumen", "Volume", "Lautstärke", "Volume", "Volume", "Głośność", "Volym"],

	# Game.
	"menu": ["‹ Menu", "‹ Menu", "‹ Menu", "‹ Menú", "‹ Menu", "‹ Menü", "‹ Menu", "‹ Menu", "‹ Menu", "‹ Meny"],
	"status_start": ["Select a number to begin.", "Seleciona um número para começar.", "Selecione um número para começar.",
			"Selecciona un número para empezar.", "Sélectionne un nombre pour commencer.", "Wähle eine Zahl, um zu beginnen.",
			"Seleziona un numero per iniziare.", "Kies een getal om te beginnen.", "Wybierz liczbę, aby zacząć.",
			"Välj ett tal för att börja."],
	"status_continue": ["Select a number to continue.", "Seleciona um número para continuar.", "Selecione um número para continuar.",
			"Selecciona un número para continuar.", "Sélectionne un nombre pour continuer.", "Wähle eine Zahl, um fortzufahren.",
			"Seleziona un numero per continuare.", "Kies een getal om verder te gaan.", "Wybierz liczbę, aby kontynuować.",
			"Välj ett tal för att fortsätta."],
	"status_operator": ["Now choose an operation.", "Agora escolhe uma operação.", "Agora escolha uma operação.",
			"Ahora elige una operación.", "Choisis maintenant une opération.", "Wähle jetzt eine Operation.", "Ora scegli un'operazione.",
			"Kies nu een bewerking.", "Teraz wybierz działanie.", "Välj nu ett räknesätt."],
	"status_second": ["Now select the second number.", "Agora seleciona o segundo número.", "Agora selecione o segundo número.",
			"Ahora selecciona el segundo número.", "Sélectionne maintenant le deuxième nombre.", "Wähle jetzt die zweite Zahl.",
			"Ora seleziona il secondo numero.", "Kies nu het tweede getal.", "Teraz wybierz drugą liczbę.", "Välj nu det andra talet."],
	"status_win": ["You reached 24!", "Chegaste ao 24!", "Você chegou ao 24!", "¡Llegaste a 24!", "Tu as atteint 24 !",
			"Du hast 24 erreicht!", "Hai raggiunto 24!", "Je hebt 24 bereikt!", "Udało ci się uzyskać 24!", "Du nådde 24!"],
	"status_div0": ["Cannot divide by 0. Choose another combination.", "Não é possível dividir por 0. Escolhe outra combinação.",
			"Não é possível dividir por 0. Escolha outra combinação.", "No se puede dividir por 0. Elige otra combinación.",
			"Impossible de diviser par 0. Choisis une autre combinaison.",
			"Division durch 0 ist nicht möglich. Wähle eine andere Kombination.",
			"Impossibile dividere per 0. Scegli un'altra combinazione.", "Delen door 0 kan niet. Kies een andere combinatie.",
			"Nie można dzielić przez 0. Wybierz inną kombinację.", "Det går inte att dela med 0. Välj en annan kombination."],
	"status_wrong": ["Got %s, not 24. Use Undo or start over.", "Deu %s, não 24. Usa Desfazer ou começa de novo.",
			"Deu %s, não 24. Use Desfazer ou comece de novo.", "Salió %s, no 24. Usa Deshacer o empieza de nuevo.",
			"Résultat %s, pas 24. Utilise Annuler ou recommence.", "%s statt 24. Nutze Rückgängig oder starte neu.",
			"Risultato %s, non 24. Usa Annulla o ricomincia.", "%s in plaats van 24. Gebruik Ongedaan maken of begin opnieuw.",
			"Wynik %s, a nie 24. Użyj Cofnij lub zacznij od nowa.", "Det blev %s, inte 24. Använd Ångra eller börja om."],
	"won_elapsed": ["You reached 24 in %s!", "Chegaste ao 24 em %s!", "Você chegou ao 24 em %s!", "¡Llegaste a 24 en %s!",
			"Tu as atteint 24 en %s !", "Du hast 24 in %s erreicht!", "Hai raggiunto 24 in %s!", "Je hebt 24 bereikt in %s!",
			"Udało ci się uzyskać 24 w %s!", "Du nådde 24 på %s!"],
	"solution_found": ["Possible solution: %s = 24", "Solução possível: %s = 24", "Solução possível: %s = 24", "Solución posible: %s = 24",
			"Solution possible : %s = 24", "Mögliche Lösung: %s = 24", "Soluzione possibile: %s = 24", "Mogelijke oplossing: %s = 24",
			"Możliwe rozwiązanie: %s = 24", "Möjlig lösning: %s = 24"],
	"solution_none": ["No solution for these numbers.", "Sem solução para estes números.", "Sem solução para estes números.",
			"No hay solución para estos números.", "Aucune solution pour ces nombres.", "Keine Lösung für diese Zahlen.",
			"Nessuna soluzione per questi numeri.", "Geen oplossing voor deze getallen.", "Brak rozwiązania dla tych liczb.",
			"Ingen lösning för de här talen."],
	"undo": ["Undo", "Desfazer", "Desfazer", "Deshacer", "Annuler", "Rückgängig", "Annulla", "Ongedaan maken", "Cofnij", "Ångra"],
	"view_solution": ["View Solution", "Ver Solução", "Ver Solução", "Ver Solución", "Voir la Solution", "Lösung Anzeigen",
			"Vedi Soluzione", "Oplossing Tonen", "Pokaż Rozwiązanie", "Visa Lösning"],
	"new_game": ["New Game", "Novo Jogo", "Novo Jogo", "Nueva Partida", "Nouvelle Partie", "Neues Spiel", "Nuova Partita", "Nieuw Spel",
			"Nowa Gra", "Nytt Spel"],
	"next_game": ["Next Game", "Próximo Jogo", "Próximo Jogo", "Siguiente Partida", "Partie Suivante", "Nächstes Spiel",
			"Partita Successiva", "Volgend Spel", "Następna Gra", "Nästa Spel"],

	# Statistics.
	"statistics": ["Statistics", "Estatísticas", "Estatísticas", "Estadísticas", "Statistiques", "Statistiken", "Statistiche",
			"Statistieken", "Statystyki", "Statistik"],
	"wins": ["Wins", "Vitórias", "Vitórias", "Victorias", "Victoires", "Siege", "Vittorie", "Overwinningen", "Wygrane", "Vinster"],
	"current_streak": ["Current streak", "Sequência atual", "Sequência atual", "Racha actual", "Série actuelle", "Aktuelle Serie",
			"Serie attuale", "Huidige reeks", "Obecna seria", "Nuvarande svit"],
	"best_streak": ["Best streak", "Melhor sequência", "Melhor sequência", "Mejor racha", "Meilleure série", "Beste Serie",
			"Serie migliore", "Beste reeks", "Najlepsza seria", "Bästa svit"],
	"win_rate": ["Win rate", "Taxa de vitória", "Taxa de vitória", "Porcentaje de victorias", "Taux de victoire", "Siegquote",
			"Percentuale vittorie", "Winstpercentage", "Procent wygranych", "Vinstandel"],
	"by_difficulty": ["By difficulty", "Por dificuldade", "Por dificuldade", "Por dificultad", "Par difficulté", "Nach Schwierigkeit",
			"Per difficoltà", "Per moeilijkheid", "Według trudności", "Per svårighetsgrad"],
	"level_detail": ["%d wins out of %d games", "%d vitórias em %d jogos", "%d vitórias em %d jogos", "%d victorias de %d partidas",
			"%d victoires sur %d parties", "%d Siege von %d Spielen", "%d vittorie su %d partite", "%d gewonnen van %d spellen",
			"%d wygranych z %d gier", "%d vinster av %d spel"],
	"recent_history": ["Recent history", "Histórico recente", "Histórico recente", "Historial reciente", "Historique récent",
			"Letzte Spiele", "Cronologia recente", "Recente spellen", "Ostatnie gry", "Senaste spel"],
	"no_games": ["No games recorded yet.", "Ainda não há jogos registados.", "Ainda não há jogos registrados.",
			"Todavía no hay partidas registradas.", "Aucune partie enregistrée pour l'instant.", "Noch keine Spiele aufgezeichnet.",
			"Nessuna partita registrata finora.", "Nog geen spellen vastgelegd.", "Brak zapisanych gier.", "Inga spel registrerade än."],
	"clear_stats": ["Clear Statistics", "Limpar Estatísticas", "Limpar Estatísticas", "Borrar Estadísticas", "Effacer les Statistiques",
			"Statistiken Löschen", "Cancella Statistiche", "Statistieken Wissen", "Wyczyść Statystyki", "Rensa Statistik"],
	"confirm_clear": ["Press again to erase everything", "Carrega outra vez para apagar tudo", "Clique de novo para apagar tudo",
			"Pulsa otra vez para borrarlo todo", "Appuie encore pour tout effacer", "Nochmal drücken, um alles zu löschen",
			"Premi di nuovo per cancellare tutto", "Druk nogmaals om alles te wissen", "Naciśnij ponownie, aby wszystko usunąć",
			"Tryck igen för att radera allt"],
	"won_lost_hint": ["Green = won, red = lost", "Verde = vitória, vermelho = derrota", "Verde = vitória, vermelho = derrota",
			"Verde = victoria, rojo = derrota", "Vert = victoire, rouge = défaite", "Grün = gewonnen, rot = verloren",
			"Verde = vittoria, rosso = sconfitta", "Groen = gewonnen, rood = verloren", "Zielony = wygrana, czerwony = przegrana",
			"Grönt = vinst, rött = förlust"],
	# Progress: daily streak, brain points, levels, badges and brain tips.
	"progress": ["Progress", "Progresso", "Progresso", "Progreso", "Progression", "Fortschritt", "Progressi", "Voortgang", "Postępy", "Framsteg"],
	"daily_streak": ["Days in a row", "Dias seguidos", "Dias seguidos", "Días seguidos", "Jours d'affilée", "Tage in Folge", "Giorni di fila", "Dagen op rij", "Dni z rzędu", "Dagar i rad"],
	"best_days": ["Best: %d days", "Melhor: %d dias", "Melhor: %d dias", "Mejor: %d días", "Record : %d jours", "Beste: %d Tage", "Migliore: %d giorni", "Beste: %d dagen", "Najlepsza: %d dni", "Bästa: %d dagar"],
	"brain_points": ["Brain points", "Pontos mentais", "Pontos mentais", "Puntos mentales", "Points cérébraux", "Denkpunkte", "Punti mente", "Breinpunten", "Punkty umysłu", "Hjärnpoäng"],
	"brain_level": ["Brain level", "Nível mental", "Nível mental", "Nivel mental", "Niveau cérébral", "Denkstufe", "Livello mentale", "Breinniveau", "Poziom umysłu", "Hjärnnivå"],
	"next_level": ["%d points to the next level", "Faltam %d pontos para o próximo nível", "Faltam %d pontos para o próximo nível", "Faltan %d puntos para el siguiente nivel", "Encore %d points pour le niveau suivant", "Noch %d Punkte bis zur nächsten Stufe", "Mancano %d punti al livello successivo", "Nog %d punten tot het volgende niveau", "Jeszcze %d pkt do następnego poziomu", "%d poäng kvar till nästa nivå"],
	"week_challenge": ["7-day challenge", "Desafio de 7 dias", "Desafio de 7 dias", "Reto de 7 días", "Défi des 7 jours", "7-Tage-Challenge", "Sfida dei 7 giorni", "7-dagenuitdaging", "Wyzwanie 7 dni", "7-dagarsutmaning"],
	"week_desc": ["Play every day for a week: 7-Day Brain badge and +100 points.", "Joga todos os dias durante uma semana: medalha Cérebro de 7 Dias e +100 pontos.", "Jogue todos os dias durante uma semana: medalha Cérebro de 7 Dias e +100 pontos.", "Juega todos los días durante una semana: insignia Cerebro de 7 Días y +100 puntos.", "Joue chaque jour pendant une semaine : badge Cerveau 7 Jours et +100 points.", "Spiele eine Woche lang jeden Tag: Abzeichen 7-Tage-Kopf und +100 Punkte.", "Gioca ogni giorno per una settimana: medaglia Mente 7 Giorni e +100 punti.", "Speel een week lang elke dag: badge 7-Dagenbrein en +100 punten.", "Graj codziennie przez tydzień: odznaka Umysł 7 Dni i +100 punktów.", "Spela varje dag i en vecka: märket 7-dagarshjärna och +100 poäng."],
	"daily_goal": ["Daily goal", "Objetivo diário", "Meta diária", "Objetivo diario", "Objectif du jour", "Tagesziel", "Obiettivo del giorno", "Dagdoel", "Cel dnia", "Dagens mål"],
	"daily_goal_desc": ["Solve %d cards today", "Resolve %d cartas hoje", "Resolva %d cartas hoje", "Resuelve %d cartas hoy", "Résous %d cartes aujourd'hui", "Löse heute %d Karten", "Risolvi %d carte oggi", "Los vandaag %d kaarten op", "Rozwiąż dziś %d karty", "Lös %d kort i dag"],
	"goal_done": ["Daily goal done! +20", "Objetivo diário cumprido! +20", "Meta diária cumprida! +20", "¡Objetivo diario cumplido! +20", "Objectif du jour atteint ! +20", "Tagesziel geschafft! +20", "Obiettivo del giorno raggiunto! +20", "Dagdoel gehaald! +20", "Cel dnia osiągnięty! +20", "Dagens mål klart! +20"],
	"badges": ["Badges", "Medalhas", "Medalhas", "Insignias", "Badges", "Abzeichen", "Medaglie", "Badges", "Odznaki", "Märken"],
	"tip_title": ["Brain tip of the day", "Dica mental do dia", "Dica mental do dia", "Consejo mental del día", "Astuce cérébrale du jour", "Denktipp des Tages", "Consiglio mentale del giorno", "Breintip van de dag", "Wskazówka dnia dla umysłu", "Dagens hjärntips"],
	"points_title": ["How to earn brain points", "Como ganhar pontos mentais", "Como ganhar pontos mentais", "Cómo ganar puntos mentales", "Comment gagner des points cérébraux", "So sammelst du Denkpunkte", "Come guadagnare punti mente", "Zo verdien je breinpunten", "Jak zdobywać punkty umysłu", "Så tjänar du hjärnpoäng"],
	"points_rules": ["Solve a card: 10 · 20 · 30 · 40 by difficulty, ×1.5 in Double Cards.\nFast: +10 under 30 s, +5 under 60 s. No solution viewed: +5.\nFirst win of the day: +5 per day of your streak (up to +35).\nUp to 500 points a day: play daily to climb the 10 brain levels.", "Resolver uma carta: 10 · 20 · 30 · 40 conforme a dificuldade, ×1,5 em Cartas Duplas.\nRapidez: +10 abaixo de 30 s, +5 abaixo de 60 s. Sem ver a solução: +5.\nPrimeira vitória do dia: +5 por cada dia seguido (até +35).\nAté 500 pontos por dia: joga todos os dias para subir os 10 níveis mentais.", "Resolver uma carta: 10 · 20 · 30 · 40 conforme a dificuldade, ×1,5 em Cartas Duplas.\nRapidez: +10 abaixo de 30 s, +5 abaixo de 60 s. Sem ver a solução: +5.\nPrimeira vitória do dia: +5 por cada dia seguido (até +35).\nAté 500 pontos por dia: jogue todos os dias para subir os 10 níveis mentais.", "Resolver una carta: 10 · 20 · 30 · 40 según la dificultad, ×1,5 en Cartas Dobles.\nRapidez: +10 en menos de 30 s, +5 en menos de 60 s. Sin ver la solución: +5.\nPrimera victoria del día: +5 por cada día de tu racha (hasta +35).\nHasta 500 puntos al día: juega cada día para subir los 10 niveles mentales.", "Résoudre une carte : 10 · 20 · 30 · 40 selon la difficulté, ×1,5 en Cartes Doubles.\nRapidité : +10 sous 30 s, +5 sous 60 s. Sans voir la solution : +5.\nPremière victoire du jour : +5 par jour de ta série (jusqu'à +35).\nJusqu'à 500 points par jour : joue chaque jour pour gravir les 10 niveaux cérébraux.", "Karte lösen: 10 · 20 · 30 · 40 je nach Stufe, ×1,5 bei Doppelkarten.\nTempo: +10 unter 30 s, +5 unter 60 s. Ohne Lösung anzusehen: +5.\nErster Sieg des Tages: +5 pro Tag deiner Serie (bis +35).\nBis zu 500 Punkte pro Tag: Spiele täglich, um die 10 Denkstufen zu erklimmen.", "Risolvi una carta: 10 · 20 · 30 · 40 secondo la difficoltà, ×1,5 in Carte Doppie.\nVelocità: +10 sotto i 30 s, +5 sotto i 60 s. Senza vedere la soluzione: +5.\nPrima vittoria del giorno: +5 per ogni giorno della serie (fino a +35).\nFino a 500 punti al giorno: gioca ogni giorno per salire i 10 livelli mentali.", "Kaart oplossen: 10 · 20 · 30 · 40 naar moeilijkheid, ×1,5 bij Dubbele Kaarten.\nSnel: +10 onder 30 s, +5 onder 60 s. Zonder oplossing te bekijken: +5.\nEerste winst van de dag: +5 per dag van je reeks (tot +35).\nTot 500 punten per dag: speel dagelijks om de 10 breinniveaus te beklimmen.", "Rozwiązana karta: 10 · 20 · 30 · 40 zależnie od poziomu, ×1,5 w Podwójnych Kartach.\nSzybkość: +10 poniżej 30 s, +5 poniżej 60 s. Bez podglądu rozwiązania: +5.\nPierwsza wygrana dnia: +5 za każdy dzień serii (do +35).\nDo 500 punktów dziennie: graj codziennie, by wspinać się po 10 poziomach umysłu.", "Lös ett kort: 10 · 20 · 30 · 40 efter svårighet, ×1,5 i Dubbelkort.\nSnabbt: +10 under 30 s, +5 under 60 s. Utan att visa lösningen: +5.\nDagens första vinst: +5 per dag i din svit (upp till +35).\nUpp till 500 poäng om dagen: spela dagligen för att klättra de 10 hjärnnivåerna."],
	"reward_total": ["+%d brain points", "+%d pontos mentais", "+%d pontos mentais", "+%d puntos mentales", "+%d points cérébraux", "+%d Denkpunkte", "+%d punti mente", "+%d breinpunten", "+%d punktów umysłu", "+%d hjärnpoäng"],
	"r_solved": ["Solved", "Resolvida", "Resolvida", "Resuelta", "Résolue", "Gelöst", "Risolta", "Opgelost", "Rozwiązana", "Löst"],
	"r_fast": ["Fast", "Rapidez", "Rapidez", "Rapidez", "Rapidité", "Tempo", "Velocità", "Snel", "Szybkość", "Snabbt"],
	"r_solo": ["No help", "Sem ajuda", "Sem ajuda", "Sin ayuda", "Sans aide", "Ohne Hilfe", "Senza aiuto", "Zonder hulp", "Bez pomocy", "Utan hjälp"],
	"r_daily": ["Daily bonus", "Bónus diário", "Bônus diário", "Bonus diario", "Bonus du jour", "Tagesbonus", "Bonus giornaliero", "Dagbonus", "Bonus dnia", "Dagsbonus"],
	"r_helped": ["Solution viewed: half points", "Solução vista: metade dos pontos", "Solução vista: metade dos pontos", "Solución vista: mitad de puntos", "Solution vue : moitié des points", "Lösung angesehen: halbe Punkte", "Soluzione vista: metà punti", "Oplossing bekeken: halve punten", "Podgląd rozwiązania: połowa punktów", "Lösningen visad: halva poängen"],
	"toast_first_day": ["Day 1 of your brain training!", "Dia 1 do teu treino mental!", "Dia 1 do seu treino mental!", "¡Día 1 de tu entrenamiento mental!", "Jour 1 de ton entraînement cérébral !", "Tag 1 deines Gehirntrainings!", "Giorno 1 del tuo allenamento mentale!", "Dag 1 van je breintraining!", "Dzień 1 twojego treningu umysłu!", "Dag 1 av din hjärnträning!"],
	"toast_streak": ["%d days in a row! Your brain says thanks.", "%d dias seguidos! O teu cérebro agradece.", "%d dias seguidos! Seu cérebro agradece.", "¡%d días seguidos! Tu cerebro te lo agradece.", "%d jours d'affilée ! Ton cerveau te dit merci.", "%d Tage in Folge! Dein Kopf sagt danke.", "%d giorni di fila! La tua mente ringrazia.", "%d dagen op rij! Je brein zegt dank je.", "%d dni z rzędu! Twój umysł dziękuje.", "%d dagar i rad! Din hjärna tackar."],
	"toast_week": ["7 days in a row! +100 brain points", "7 dias seguidos! +100 pontos mentais", "7 dias seguidos! +100 pontos mentais", "¡7 días seguidos! +100 puntos mentales", "7 jours d'affilée ! +100 points cérébraux", "7 Tage in Folge! +100 Denkpunkte", "7 giorni di fila! +100 punti mente", "7 dagen op rij! +100 breinpunten", "7 dni z rzędu! +100 punktów umysłu", "7 dagar i rad! +100 hjärnpoäng"],
	"toast_badge": ["New badge: %s", "Nova medalha: %s", "Nova medalha: %s", "Nueva insignia: %s", "Nouveau badge : %s", "Neues Abzeichen: %s", "Nuova medaglia: %s", "Nieuwe badge: %s", "Nowa odznaka: %s", "Nytt märke: %s"],
	"toast_rank": ["New brain level: %s", "Novo nível mental: %s", "Novo nível mental: %s", "Nuevo nivel mental: %s", "Nouveau niveau cérébral : %s", "Neue Denkstufe: %s", "Nuovo livello mentale: %s", "Nieuw breinniveau: %s", "Nowy poziom umysłu: %s", "Ny hjärnnivå: %s"],
	"rank_1": ["Curious Mind", "Mente Curiosa", "Mente Curiosa", "Mente Curiosa", "Esprit Curieux", "Neugieriger Kopf", "Mente Curiosa", "Nieuwsgierig Brein", "Ciekawy Umysł", "Nyfiken Hjärna"],
	"rank_2": ["Number Explorer", "Explorador de Números", "Explorador de Números", "Explorador de Números", "Explorateur de Nombres", "Zahlenentdecker", "Esploratore di Numeri", "Getallenontdekker", "Odkrywca Liczb", "Talutforskare"],
	"rank_3": ["Quick Calculator", "Calculador Rápido", "Calculador Rápido", "Calculador Rápido", "Calculateur Rapide", "Schneller Rechner", "Calcolatore Rapido", "Snelle Rekenaar", "Szybki Rachmistrz", "Snabb Räknare"],
	"rank_4": ["Sharp Thinker", "Pensador Perspicaz", "Pensador Perspicaz", "Pensador Agudo", "Esprit Aiguisé", "Scharfer Denker", "Pensatore Acuto", "Scherpe Denker", "Bystry Myśliciel", "Skarp Tänkare"],
	"rank_5": ["Math Strategist", "Estratega da Matemática", "Estrategista da Matemática", "Estratega Matemático", "Stratège des Maths", "Mathe-Stratege", "Stratega della Matematica", "Rekenstrateeg", "Strateg Matematyki", "Mattestrateg"],
	"rank_6": ["Number Wizard", "Mago dos Números", "Mago dos Números", "Mago de los Números", "Magicien des Nombres", "Zahlenzauberer", "Mago dei Numeri", "Getallentovenaar", "Czarodziej Liczb", "Taltrollkarl"],
	"rank_7": ["Math Master", "Mestre da Matemática", "Mestre da Matemática", "Maestro de las Matemáticas", "Maître des Maths", "Mathe-Meister", "Maestro della Matematica", "Rekenmeester", "Mistrz Matematyki", "Mattemästare"],
	"rank_8": ["Mental Athlete", "Atleta Mental", "Atleta Mental", "Atleta Mental", "Athlète Mental", "Denksportler", "Atleta Mentale", "Mentale Atleet", "Atleta Umysłu", "Mental Atlet"],
	"rank_9": ["Human Calculator", "Calculadora Humana", "Calculadora Humana", "Calculadora Humana", "Calculatrice Humaine", "Menschlicher Rechner", "Calcolatrice Umana", "Menselijke Rekenmachine", "Ludzki Kalkulator", "Mänsklig Miniräknare"],
	"rank_10": ["Brain Champion", "Campeão Mental", "Campeão Mental", "Campeón Mental", "Champion Cérébral", "Denk-Champion", "Campione della Mente", "Breinkampioen", "Czempion Umysłu", "Hjärnmästare"],
	"rank_legend": ["Brain Legend", "Lenda Mental", "Lenda Mental", "Leyenda Mental", "Légende Cérébrale", "Denk-Legende", "Leggenda della Mente", "Breinlegende", "Legenda Umysłu", "Hjärnlegend"],
	"today_points": ["Today: %d / %d", "Hoje: %d / %d", "Hoje: %d / %d", "Hoy: %d / %d", "Aujourd'hui : %d / %d", "Heute: %d / %d", "Oggi: %d / %d", "Vandaag: %d / %d", "Dziś: %d / %d", "I dag: %d / %d"],
	"r_capped": ["Daily limit reached: come back tomorrow for more points", "Limite diário atingido: volta amanhã para mais pontos", "Limite diário atingido: volte amanhã para mais pontos", "Límite diario alcanzado: vuelve mañana para más puntos", "Limite du jour atteinte : reviens demain pour plus de points", "Tageslimit erreicht: Komm morgen für mehr Punkte wieder", "Limite giornaliero raggiunto: torna domani per altri punti", "Daglimiet bereikt: kom morgen terug voor meer punten", "Dzienny limit osiągnięty: wróć jutro po więcej punktów", "Dagsgränsen nådd: kom tillbaka i morgon för fler poäng"],
	"b_first": ["First 24", "Primeiro 24", "Primeiro 24", "Primer 24", "Premier 24", "Erste 24", "Primo 24", "Eerste 24", "Pierwsze 24", "Första 24"],
	"b_first_desc": ["Solve your first card.", "Resolve a tua primeira carta.", "Resolva sua primeira carta.", "Resuelve tu primera carta.", "Résous ta première carte.", "Löse deine erste Karte.", "Risolvi la tua prima carta.", "Los je eerste kaart op.", "Rozwiąż pierwszą kartę.", "Lös ditt första kort."],
	"b_week": ["7-Day Brain", "Cérebro de 7 Dias", "Cérebro de 7 Dias", "Cerebro de 7 Días", "Cerveau 7 Jours", "7-Tage-Kopf", "Mente 7 Giorni", "7-Dagenbrein", "Umysł 7 Dni", "7-dagarshjärna"],
	"b_week_desc": ["Play 7 days in a row.", "Joga 7 dias seguidos.", "Jogue 7 dias seguidos.", "Juega 7 días seguidos.", "Joue 7 jours d'affilée.", "Spiele 7 Tage in Folge.", "Gioca 7 giorni di fila.", "Speel 7 dagen op rij.", "Graj 7 dni z rzędu.", "Spela 7 dagar i rad."],
	"b_quick": ["Quick Thinker", "Pensador Rápido", "Pensador Rápido", "Pensador Rápido", "Esprit Vif", "Schnelldenker", "Pensatore Veloce", "Snelle Denker", "Bystry Umysł", "Snabbtänkare"],
	"b_quick_desc": ["Solve a card in under 20 seconds.", "Resolve uma carta em menos de 20 segundos.", "Resolva uma carta em menos de 20 segundos.", "Resuelve una carta en menos de 20 segundos.", "Résous une carte en moins de 20 secondes.", "Löse eine Karte in unter 20 Sekunden.", "Risolvi una carta in meno di 20 secondi.", "Los een kaart op in minder dan 20 seconden.", "Rozwiąż kartę w mniej niż 20 sekund.", "Lös ett kort på under 20 sekunder."],
	"b_solo": ["Solo Mind", "Mente Autónoma", "Mente Autônoma", "Mente Autónoma", "Esprit Autonome", "Eigenständiger Kopf", "Mente Autonoma", "Zelfstandig Brein", "Samodzielny Umysł", "Självständig Hjärna"],
	"b_solo_desc": ["Solve 10 cards without viewing the solution.", "Resolve 10 cartas sem ver a solução.", "Resolva 10 cartas sem ver a solução.", "Resuelve 10 cartas sin ver la solución.", "Résous 10 cartes sans voir la solution.", "Löse 10 Karten, ohne die Lösung anzusehen.", "Risolvi 10 carte senza vedere la soluzione.", "Los 10 kaarten op zonder de oplossing te bekijken.", "Rozwiąż 10 kart bez podglądu rozwiązania.", "Lös 10 kort utan att visa lösningen."],
	"b_double": ["Double Trouble", "Dose Dupla", "Dose Dupla", "Doble Desafío", "Double Défi", "Doppelt Stark", "Doppia Sfida", "Dubbel Sterk", "Podwójne Wyzwanie", "Dubbelt Upp"],
	"b_double_desc": ["Win a Double Cards round.", "Ganha uma ronda de Cartas Duplas.", "Vença uma rodada de Cartas Duplas.", "Gana una ronda de Cartas Dobles.", "Gagne une manche en Cartes Doubles.", "Gewinne eine Runde Doppelkarten.", "Vinci un round di Carte Doppie.", "Win een ronde Dubbele Kaarten.", "Wygraj rundę Podwójnych Kart.", "Vinn en omgång Dubbelkort."],
	"b_expert": ["Very Hard Genius", "Génio do Muito Difícil", "Gênio do Muito Difícil", "Genio Muy Difícil", "Génie Très Difficile", "Sehr-Schwer-Genie", "Genio Molto Difficile", "Zeer-Moeilijk-Genie", "Geniusz Bardzo Trudny", "Mycket Svår-geni"],
	"b_expert_desc": ["Solve a Very Hard card.", "Resolve uma carta Muito Difícil.", "Resolva uma carta Muito Difícil.", "Resuelve una carta Muy Difícil.", "Résous une carte Très Difficile.", "Löse eine Karte auf Sehr Schwer.", "Risolvi una carta Molto Difficile.", "Los een Zeer Moeilijke kaart op.", "Rozwiąż kartę Bardzo Trudną.", "Lös ett Mycket Svårt kort."],
	"tip_1": ["Mental arithmetic trains your working memory: you hold numbers in your head while you plan the next step.", "O cálculo mental treina a memória de trabalho: guardas números na cabeça enquanto planeias o passo seguinte.", "O cálculo mental treina a memória de trabalho: você guarda números na cabeça enquanto planeja o próximo passo.", "El cálculo mental entrena la memoria de trabajo: retienes números en la cabeza mientras planeas el siguiente paso.", "Le calcul mental entraîne la mémoire de travail : tu gardes des nombres en tête pendant que tu prépares l'étape suivante.", "Kopfrechnen trainiert das Arbeitsgedächtnis: Du behältst Zahlen im Kopf, während du den nächsten Schritt planst.", "Il calcolo mentale allena la memoria di lavoro: tieni i numeri a mente mentre pianifichi il passo successivo.", "Hoofdrekenen traint je werkgeheugen: je houdt getallen vast terwijl je de volgende stap plant.", "Liczenie w pamięci ćwiczy pamięć roboczą: trzymasz liczby w głowie, planując kolejny krok.", "Huvudräkning tränar arbetsminnet: du håller tal i huvudet medan du planerar nästa steg."],
	"tip_2": ["Work backwards: 24 is 3 × 8, 4 × 6, 2 × 12 or 30 − 6. Look for the pair that gets you there.", "Pensa ao contrário: 24 é 3 × 8, 4 × 6, 2 × 12 ou 30 − 6. Procura o par que te leva lá.", "Pense ao contrário: 24 é 3 × 8, 4 × 6, 2 × 12 ou 30 − 6. Procure o par que leva você até lá.", "Piensa al revés: 24 es 3 × 8, 4 × 6, 2 × 12 o 30 − 6. Busca el par que te lleva allí.", "Pense à l'envers : 24, c'est 3 × 8, 4 × 6, 2 × 12 ou 30 − 6. Cherche la paire qui t'y mène.", "Denk rückwärts: 24 ist 3 × 8, 4 × 6, 2 × 12 oder 30 − 6. Such das Paar, das dich dorthin bringt.", "Ragiona al contrario: 24 è 3 × 8, 4 × 6, 2 × 12 o 30 − 6. Cerca la coppia che ti ci porta.", "Denk terug: 24 is 3 × 8, 4 × 6, 2 × 12 of 30 − 6. Zoek het paar dat je daar brengt.", "Myśl od końca: 24 to 3 × 8, 4 × 6, 2 × 12 albo 30 − 6. Szukaj pary, która cię tam doprowadzi.", "Tänk baklänges: 24 är 3 × 8, 4 × 6, 2 × 12 eller 30 − 6. Leta efter paret som tar dig dit."],
	"tip_3": ["A little every day beats a lot once in a while: a few cards a day keep your number sense sharp.", "Um pouco todos os dias vale mais do que muito de vez em quando: algumas cartas por dia mantêm o teu sentido numérico afinado.", "Um pouco todo dia vale mais do que muito de vez em quando: algumas cartas por dia mantêm seu senso numérico afiado.", "Un poco cada día vale más que mucho de vez en cuando: unas cartas al día mantienen afinado tu sentido numérico.", "Un peu chaque jour vaut mieux que beaucoup de temps en temps : quelques cartes par jour gardent ton sens des nombres affûté.", "Jeden Tag ein bisschen bringt mehr als ab und zu viel: ein paar Karten am Tag halten dein Zahlengefühl scharf.", "Un po' ogni giorno vale più di tanto ogni tanto: qualche carta al giorno tiene allenato il tuo senso dei numeri.", "Elke dag een beetje werkt beter dan af en toe veel: een paar kaarten per dag houden je getalgevoel scherp.", "Trochę każdego dnia daje więcej niż dużo od czasu do czasu: kilka kart dziennie utrzymuje wyczucie liczb.", "Lite varje dag slår mycket då och då: några kort om dagen håller din talkänsla skarp."],
	"tip_4": ["Fractions are allowed along the way: 8 ÷ (3 − 8 ÷ 3) is exactly 24.", "As frações são permitidas pelo caminho: 8 ÷ (3 − 8 ÷ 3) dá exatamente 24.", "Frações são permitidas no caminho: 8 ÷ (3 − 8 ÷ 3) dá exatamente 24.", "Las fracciones valen por el camino: 8 ÷ (3 − 8 ÷ 3) da exactamente 24.", "Les fractions sont permises en chemin : 8 ÷ (3 − 8 ÷ 3) fait exactement 24.", "Brüche sind unterwegs erlaubt: 8 ÷ (3 − 8 ÷ 3) ergibt genau 24.", "Le frazioni sono ammesse lungo il percorso: 8 ÷ (3 − 8 ÷ 3) fa esattamente 24.", "Breuken mogen onderweg: 8 ÷ (3 − 8 ÷ 3) is precies 24.", "Ułamki są dozwolone po drodze: 8 ÷ (3 − 8 ÷ 3) to dokładnie 24.", "Bråk är tillåtna på vägen: 8 ÷ (3 − 8 ÷ 3) blir exakt 24."],
}


static var installed := false


## Registers all languages with Godot's TranslationServer (once).
static func install() -> void:
	if installed:
		return
	installed = true
	for i in LANGUAGES.size():
		var translation := Translation.new()
		translation.locale = LANGUAGES[i][0]
		for key: String in TEXT:
			translation.add_message(key, TEXT[key][i])
		TranslationServer.add_translation(translation)


## The player's system language if the game has it (Brazilian Portuguese before plain Portuguese), otherwise English.
static func system_language() -> String:
	var locale := OS.get_locale()
	var lang := OS.get_locale_language()
	for code in [locale, lang]:
		for entry in LANGUAGES:
			if entry[0] == code:
				return code
	return "en"
