extends RefCounted
## Every text in the game, in each language. The game shows them with tr("key").
## Values follow the order of LANGUAGES. Weapon names are the same in every language (weapons.gd).

const LANGUAGES := [["en", "English"], ["pt", "Português"]]

const TEXT := {
	# Menu.
	"tagline": ["Plant the bomb or stop it. Five against five, one life per round.",
			"Planta a bomba ou trava-a. Cinco contra cinco, uma vida por ronda."],
	"play": ["Play", "Jogar"],
	"how_to_play": ["How to Play", "Como Jogar"],
	"settings": ["Settings", "Definições"],
	"quit": ["Quit", "Sair"],
	"back": ["Back", "Voltar"],
	"record": ["Matches won %d · lost %d · drawn %d", "Partidas ganhas %d · perdidas %d · empatadas %d"],
	"hint_keys": ["Arrows move · Enter selects · Esc goes back", "Setas movem · Enter escolhe · Esc volta atrás"],
	"hint_pad": ["D-pad moves · A selects · B goes back", "D-pad move · A escolhe · B volta atrás"],

	# Match setup.
	"match_setup": ["New Match", "Nova Partida"],
	"map": ["Map", "Mapa"],
	"map_dunes": ["Dunes", "Dunas"],
	"map_depot": ["Depot", "Armazém"],
	"side": ["Your side", "O teu lado"],
	"side_att": ["Attackers", "Atacantes"],
	"side_def": ["Defenders", "Defensores"],
	"side_auto": ["Random", "Aleatório"],
	"team_size": ["Teams", "Equipas"],
	"size_n": ["%d vs %d", "%d contra %d"],
	"bot_skill": ["Bot skill", "Nível dos bots"],
	"skill_0": ["Easy", "Fácil"],
	"skill_1": ["Normal", "Normal"],
	"skill_2": ["Hard", "Difícil"],
	"skill_3": ["Expert", "Perito"],
	"match_length": ["Match length", "Duração"],
	"length_0": ["Short: first to 9 of 16 rounds", "Curta: primeiro a 9 de 16 rondas"],
	"length_1": ["Long: first to 16 of 30 rounds", "Longa: primeiro a 16 de 30 rondas"],
	"start_match": ["Start Match", "Começar Partida"],

	# Pause and match end.
	"paused": ["Paused", "Pausa"],
	"resume": ["Resume", "Continuar"],
	"quit_to_menu": ["Leave Match", "Abandonar Partida"],
	"victory": ["Victory", "Vitória"],
	"defeat": ["Defeat", "Derrota"],
	"draw": ["Draw", "Empate"],
	"your_stats": ["Your kills %d · deaths %d", "Os teus abates %d · mortes %d"],
	"play_again": ["Play Again", "Jogar Outra Vez"],
	"main_menu": ["Main Menu", "Menu Principal"],
	"click_to_play": ["Click to play", "Clica para jogar"],

	# Rounds.
	"you": ["You", "Tu"],
	"round_n": ["Round %d", "Ronda %d"],
	"round_short": ["Round %d / %d", "Ronda %d / %d"],
	"last_round": ["Last round", "Última ronda"],
	"last_round_half": ["Last round of the half", "Última ronda da primeira parte"],
	"match_point": ["Round %d · Match point", "Ronda %d · Ponto de partida"],
	"buy_hint": ["Buy your gear", "Compra o teu equipamento"],
	"go": ["Go, go, go!", "Vamos, vamos!"],
	"att_win": ["Attackers win", "Os atacantes ganham"],
	"def_win": ["Defenders win", "Os defensores ganham"],
	"reason_elimination": ["Every enemy is down", "Todos os inimigos foram abatidos"],
	"reason_bomb": ["The target was destroyed", "O alvo foi destruído"],
	"reason_defuse": ["The bomb was defused", "A bomba foi desativada"],
	"reason_time": ["Time ran out", "O tempo acabou"],
	"bomb_planted": ["Bomb planted", "Bomba plantada"],
	"site_n": ["Site %s", "Local %s"],
	"halftime": ["Half time: the teams switch sides.", "Intervalo: as equipas trocam de lado."],
	"got_bomb": ["You picked up the bomb.", "Apanhaste a bomba."],
	"plant_on_site": ["The bomb can only be planted on a bomb site (A or B).", "A bomba só pode ser plantada num local de bomba (A ou B)."],

	# HUD.
	"hud_bomb": ["BOMB", "BOMBA"],
	"hud_buy": ["%s  buy menu", "%s  menu de compras"],
	"planting": ["Planting the bomb", "A plantar a bomba"],
	"defusing": ["Defusing", "A desativar"],
	"no_time": ["Not enough time!", "Não há tempo suficiente!"],
	"hint_defuse": ["Hold %s to defuse the bomb", "Mantém %s para desativar a bomba"],
	"hint_take_bomb": ["You are on a bomb site: press %s for the bomb", "Estás num local de bomba: carrega %s para a bomba"],
	"hint_plant": ["Hold fire to plant the bomb", "Mantém o disparo para plantar a bomba"],
	"hint_pickup": ["%s  pick up %s", "%s  apanhar %s"],
	"hint_next": ["click for the next player", "clica para o jogador seguinte"],
	"you_died": ["You died", "Morreste"],
	"killed_by": ["Killed by %s (%d HP left)", "Abatido por %s (ficou com %d de vida)"],
	"spectating": ["Watching %s", "A ver %s"],
	"col_kills": ["K", "A"],
	"col_deaths": ["D", "M"],
	"col_money": ["Money", "Dinheiro"],

	# Buy menu.
	"buy_title": ["Buy", "Comprar"],
	"buy_pistols": ["Pistols", "Pistolas"],
	"buy_heavy": ["SMGs and shotgun", "Submetralhadoras e caçadeira"],
	"buy_rifles": ["Rifles", "Espingardas"],
	"buy_gear": ["Gear and grenades", "Equipamento e granadas"],
	"buy_close_hint": ["B or Esc closes · buying is open during freeze time and the first 20 seconds, in your spawn",
			"B ou Esc fecha · as compras estão abertas no início da ronda e nos primeiros 20 segundos, na tua base"],
	"owned": ["owned", "já tens"],

	# How to play.
	"help_goal": ["Goal", "Objetivo"],
	"help_goal_text": ["Two teams play a series of rounds, and you have one life per round. Attackers win a round by planting the bomb on site A or B and keeping it safe until it explodes, or by taking out every defender. Defenders win by defusing a planted bomb, by taking out every attacker before the bomb is down, or when the round clock runs out. At half time the teams switch sides.",
			"Duas equipas jogam uma série de rondas e tens uma vida por ronda. Os atacantes ganham a ronda plantando a bomba no local A ou B e protegendo-a até explodir, ou abatendo todos os defensores. Os defensores ganham desativando a bomba plantada, abatendo todos os atacantes antes de a bomba ser plantada, ou quando o relógio da ronda chega ao fim. No intervalo as equipas trocam de lado."],
	"help_money": ["Money", "Dinheiro"],
	"help_money_text": ["Buy weapons, armor and grenades at the start of each round, in your spawn. Kills pay (SMGs and the shotgun pay more, the sniper rifle less), winning pays best, and losing rounds in a row pays more each time. Survivors keep their weapons for the next round; if you die you start with a pistol again.",
			"Compra armas, colete e granadas no início de cada ronda, na tua base. Os abates dão dinheiro (as submetralhadoras e a caçadeira dão mais, a espingarda de precisão menos), ganhar dá mais ainda, e perder rondas seguidas dá cada vez mais. Quem sobrevive mantém as armas para a ronda seguinte; se morreres começas outra vez só com a pistola."],
	"help_shooting": ["Shooting", "Disparar"],
	"help_shooting_text": ["Stand still, walk or crouch to shoot straight: running and jumping throw your shots off. Guns climb as you spray, so fire short bursts or pull down against the recoil. A headshot does four times the damage, and a helmet only softens it. Walking is silent; running footsteps give you away.",
			"Fica parado, anda devagar ou agacha-te para disparar certeiro: correr e saltar desviam os tiros. As armas sobem enquanto disparas em rajada, por isso dispara rajadas curtas ou puxa para baixo contra o recuo. Um tiro na cabeça faz quatro vezes o dano, e o capacete só o atenua. Andar devagar é silencioso; os passos a correr denunciam-te."],
	"controls": ["Controls", "Controlos"],
	"help_keyboard": ["Keyboard and mouse: WASD to move, mouse to aim, left click to fire, right click to zoom, R to reload, Space to jump, Ctrl to crouch, Shift to walk quietly, 1–5 or the mouse wheel to change weapon (5 is the bomb), Q for the last weapon, G to drop your weapon, E to pick up or to defuse (hold), B for the buy menu, Tab for the scores, Esc to pause.",
			"Teclado e rato: WASD para andar, rato para apontar, clique esquerdo para disparar, clique direito para o zoom, R para recarregar, Espaço para saltar, Ctrl para agachar, Shift para andar em silêncio, 1–5 ou a roda do rato para trocar de arma (5 é a bomba), Q para a arma anterior, G para largar a arma, E para apanhar ou desativar (manter), B para o menu de compras, Tab para a pontuação, Esc para pausa."],
	"help_pad": ["Controller: left stick to move, right stick to aim, RT to fire, LT to zoom, X to reload, A to jump, B to crouch, click the left stick to walk, LB / RB or Y to change weapon, D-pad up to pick up or defuse, D-pad down for the scores, View for the buy menu, Start to pause.",
			"Comando: manípulo esquerdo para andar, manípulo direito para apontar, RT para disparar, LT para o zoom, X para recarregar, A para saltar, B para agachar, clicar no manípulo esquerdo para andar devagar, LB / RB ou Y para trocar de arma, D-pad para cima para apanhar ou desativar, D-pad para baixo para a pontuação, View para o menu de compras, Start para pausa."],

	# Settings.
	"language": ["Language", "Idioma"],
	"sound": ["Sound effects", "Efeitos sonoros"],
	"mouse_sensitivity": ["Mouse sensitivity", "Sensibilidade do rato"],
	"stick_sensitivity": ["Stick sensitivity", "Sensibilidade do manípulo"],
	"invert_y": ["Invert aim", "Inverter mira"],
	"fullscreen": ["Fullscreen", "Ecrã inteiro"],
	"on": ["On", "Ligado"],
	"off": ["Off", "Desligado"],
	"about_text": ["Dead Sector is a round-based tactical shooter: attackers plant the bomb, defenders stop them.",
			"Dead Sector é um jogo de tiros tático por rondas: os atacantes plantam a bomba, os defensores impedem-nos."],
	"developed_by": ["Developed by Web Platinum.", "Desenvolvido por Web Platinum."],

	# Campaign: menus.
	"campaign": ["Campaign", "Campanha"],
	"skirmish": ["Skirmish", "Escaramuça"],
	"campaign_tagline": ["2047. Sector 17 went dark six months ago. Tonight, a transmission: \"They're still alive.\"",
			"2047. O Setor 17 apagou-se há seis meses. Esta noite, uma transmissão: \"Ainda estão vivos.\""],
	"continue": ["Continue", "Continuar"],
	"continue_at": ["Continue: %s", "Continuar: %s"],
	"new_campaign": ["New Campaign", "Nova Campanha"],
	"mission_select": ["Mission Select", "Escolher Missão"],
	"intel_archive": ["Intel Archive", "Arquivo de Informações"],
	"difficulty": ["Difficulty", "Dificuldade"],
	"diff_0": ["Recruit", "Recruta"],
	"diff_1": ["Soldier", "Soldado"],
	"diff_2": ["Veteran", "Veterano"],
	"diff_3": ["Black Division", "Divisão Negra"],
	"deploy": ["Deploy", "Avançar"],
	"locked": ["Locked", "Bloqueada"],
	"mission_short": ["Mission %d", "Missão %d"],
	"best": ["best %s · intel %d/3", "melhor %s · informações %d/3"],
	"mission_complete": ["Mission Complete", "Missão Cumprida"],
	"next_mission": ["Next Mission", "Missão Seguinte"],
	"replay_mission": ["Play Again", "Jogar Outra Vez"],
	"restart_checkpoint": ["Restart Checkpoint", "Recomeçar do Ponto de Controlo"],
	"stat_time": ["Time", "Tempo"],
	"stat_kills": ["Kills", "Abates"],
	"stat_headshots": ["Headshots", "Tiros na cabeça"],
	"stat_accuracy": ["Accuracy", "Precisão"],
	"stat_deaths": ["Deaths", "Mortes"],
	"stat_intel": ["Intel found", "Informações encontradas"],
	"campaign_done": ["More missions of the campaign are on the way.", "Mais missões da campanha estão a caminho."],
	"no_intel": ["No intel found yet. Look for folders marked CLASSIFIED.", "Ainda não encontraste informações. Procura pastas marcadas CONFIDENCIAL."],

	# Campaign: in the field.
	"objective": ["Objective", "Objetivo"],
	"new_objective": ["New objective", "Novo objetivo"],
	"checkpoint": ["Checkpoint", "Ponto de controlo"],
	"intel_found": ["Intel found: %s", "Informação encontrada: %s"],
	"got_ammo": ["+ %s ammo", "+ munições de %s"],
	"low_ammo": ["Low on ammo: walk over dropped enemy guns for ammo, or press E to take one", "Poucas munições: passa por cima das armas largadas pelos inimigos para recolher munições, ou carrega E para pegar numa"],
	"got_ammo_box": ["Ammo and a grenade", "Munições e uma granada"],
	"got_medkit": ["Medkit: +50 health", "Kit médico: +50 de vida"],
	"got_armor": ["Armor and helmet", "Colete e capacete"],
	"got_mask": ["Gas mask: the gas can't hurt you now", "Máscara de gás: o gás já não te faz mal"],
	"got_key_red": ["Red keycard", "Cartão vermelho"],
	"got_key_blue": ["Blue keycard", "Cartão azul"],
	"got_key_yellow": ["Yellow keycard", "Cartão amarelo"],
	"door_unlocked": ["Door unlocked", "Porta desbloqueada"],
	"needs_key_red": ["Needs the red keycard", "Precisa do cartão vermelho"],
	"needs_key_blue": ["Needs the blue keycard", "Precisa do cartão azul"],
	"needs_key_yellow": ["Needs the yellow keycard", "Precisa do cartão amarelo"],
	"needs_gasmask": ["You need a gas mask", "Precisas de uma máscara de gás"],
	"hold_to": ["Hold %s: %s", "Mantém %s: %s"],
	"use_generic": ["use", "usar"],
	"remaining": ["%d left", "faltam %d"],
	"enemy_rogue": ["Security", "Segurança"],
	"enemy_sniper": ["Security sniper", "Atirador da segurança"],
	"enemy_black": ["Black Division", "Divisão Negra"],
	"enemy_army": ["Soldier", "Soldado"],
	"enemy_infected": ["Infected", "Infetado"],
	"enemy_mutant": ["Mutant", "Mutante"],
	"enemy_first": ["The First", "O Primeiro"],
	"machine_turret": ["Turret", "Torreta"],
	"machine_drone": ["Drone", "Drone"],
	"machine_conduit": ["Conduit", "Conduta"],
	"behemoth": ["???", "???"],
	"weapon_fire": ["fire", "fogo"],
	"weapon_steam": ["steam", "vapor"],
	"weapon_arc": ["electricity", "eletricidade"],
	"weapon_gas": ["gas", "gás"],
	"weapon_debris": ["debris", "destroços"],
	"weapon_fall": ["fall", "queda"],
	"weapon_strike": ["air strike", "ataque aéreo"],
	"weapon_behemoth": ["???", "???"],
	"weapon_turret": ["turret", "torreta"],
	"weapon_drone": ["drone", "drone"],
	"spk_mercer": ["Mercer", "Mercer"],
	"spk_reyes": ["Sgt. Reyes", "Sgt. Reyes"],
	"spk_volkov": ["Cpl. Volkov", "Cabo Volkov"],
	"spk_hale": ["Col. Hale (Overwatch)", "Cor. Hale (Overwatch)"],
	"spk_pilot": ["Raptor 2-1", "Raptor 2-1"],
	"spk_okafor": ["Lt. Okafor", "Ten. Okafor"],
	"spk_radio": ["Radio", "Rádio"],
	"spk_tv": ["TV", "TV"],
	"spk_voss": ["Dr. Voss (recording)", "Dra. Voss (gravação)"],
	"spk_first": ["The First", "O Primeiro"],

	# LEVEL 01 — THE DROP.
	"m01_title": ["LEVEL 01 — THE DROP", "NÍVEL 01 — A QUEDA"],
	"m01_location": ["Outskirts of the Dead Sector · 02:40", "Arredores do Setor Morto · 02:40"],
	"m01_brief": ["Six months ago an accident at Sector 17, a classified research site beneath an abandoned industrial city, killed everyone inside. The region was sealed and declared a Dead Sector. Tonight a transmission came out of it: \"They're still alive.\" The reconnaissance team sent in, Echo, has disappeared.\n\nYou are Captain Jack Mercer, Black Division. Your orders: find Echo, find out what happened, recover Project HELIX. If recovery isn't possible, destroy the facility.",
			"Há seis meses, um acidente no Setor 17, uma instalação de investigação secreta por baixo de uma cidade industrial abandonada, matou toda a gente lá dentro. A região foi selada e declarada Setor Morto. Esta noite saiu de lá uma transmissão: \"Ainda estão vivos.\" A equipa de reconhecimento enviada, a Echo, desapareceu.\n\nÉs o Capitão Jack Mercer, da Divisão Negra. As tuas ordens: encontrar a Echo, descobrir o que aconteceu, recuperar o Projeto HELIX. Se não for possível, destruir as instalações."],
	"m01_c1": ["Mercer, Overwatch. Echo's last signal came from the quarantine checkpoint. Find them. Nothing else leaves that sector.", "Mercer, aqui Overwatch. O último sinal da Echo veio do posto de quarentena. Encontrem-nos. Mais nada sai daquele setor."],
	"m01_c2": ["Two minutes. Highway's lit up like Christmas down there.", "Dois minutos. A autoestrada lá em baixo está toda acesa."],
	"m01_c3": ["Those are fires. Whole lanes of cars, just... left there.", "Aquilo são fogos. Filas inteiras de carros, simplesmente... abandonados."],
	"m01_c4": ["Six months and it's still burning? Who's feeding it?", "Seis meses e ainda está a arder? Quem é que o alimenta?"],
	"m01_c5": ["Missile! Brace, brace, brace!", "Míssil! Preparar para o impacto!"],
	"m01_l1": ["Mercer! Mercer, you with me? Get up, we can't stay by the wreck.", "Mercer! Mercer, estás aí? Levanta-te, não podemos ficar junto aos destroços."],
	"m01_l2": ["Pilot's gone. That was no accident — somebody down here has launchers.", "O piloto morreu. Aquilo não foi acidente — alguém aqui em baixo tem lança-mísseis."],
	"m01_l3": ["Radio's dead. Weapons check. Stay close to the wreck's cover.", "O rádio está morto. Verifiquem as armas. Fiquem perto dos destroços."],
	"m01_l4": ["Contact north! They're coming down the road to finish us!", "Contacto a norte! Vêm pela estrada para acabar connosco!"],
	"m01_l5": ["Sector security. Our side. Why the hell are they shooting at us?", "Segurança do setor. São dos nossos. Porque raio estão a disparar contra nós?"],
	"m01_l6": ["Mercer, Overwatch. We saw Raptor go down. No extraction until you reach the checkpoint.", "Mercer, aqui Overwatch. Vimos o Raptor cair. Não há extração até chegarem ao posto."],
	"m01_l7": ["Security in the sector is compromised. Anyone armed is hostile. Move north.", "A segurança do setor está comprometida. Quem estiver armado é hostil. Avancem para norte."],
	"m01_l8": ["Gas station's been stripped. Someone's been living off this road.", "A bomba de gasolina foi saqueada. Alguém tem vivido desta estrada."],
	"m01_l9": ["Roadblock ahead. Barriers, a truck, a shooter on the right. Take it slow.", "Barreira à frente. Barreiras, um camião, um atirador à direita. Com calma."],
	"m01_l10": ["Road's clear. The checkpoint's up ahead — the container wall.", "Estrada limpa. O posto é já ali — a parede de contentores."],
	"m01_l11": ["Checkpoint... God. These men have been dead for weeks.", "O posto... meu Deus. Estes homens estão mortos há semanas."],
	"m01_l12": ["Nobody came back for them. And security's picking over their gear.", "Ninguém voltou para os buscar. E a segurança anda a revistar-lhes o equipamento."],
	"m01_l13": ["Echo's last position is on the other side of that gate. Clear the area.", "A última posição da Echo é do outro lado daquele portão. Limpem a zona."],
	"m01_l14": ["Area's clear. Gate's sealed from the inside.", "Zona limpa. O portão está trancado por dentro."],
	"m01_l15": ["Gunfire. Inside! Someone's fighting in there!", "Tiros. Lá dentro! Há alguém a combater!"],
	"m01_l16": ["What the hell was that?!", "Que raio foi aquilo?!"],
	"m01_l17": ["It ran on all fours. Nothing runs like that.", "Corria de quatro. Nada corre assim."],
	"m01_l18": ["Mercer, report. Mercer? ...Proceed into the quarantine zone. That's an order.", "Mercer, relatório. Mercer? ...Avancem para a zona de quarentena. É uma ordem."],
	"m01_o1": ["Survive the ambush at the crash site", "Sobrevive à emboscada no local da queda"],
	"m01_o2": ["Follow the highway north", "Segue a autoestrada para norte"],
	"m01_o3": ["Reach the quarantine checkpoint", "Chega ao posto de quarentena"],
	"m01_o4": ["Clear the checkpoint and find a way inside", "Limpa o posto e encontra uma entrada"],
	"m01_i1_title": ["Evacuation Order 17-C", "Ordem de Evacuação 17-C"],
	"m01_i1_body": ["All civilians within the Sector 17 radius will proceed to Highway 9 by 06:00. Personal vehicles will be abandoned at the checkpoint. This is a precaution. There is no danger to the public. — Regional Authority. (Scrawled underneath: they closed the road at 05:00.)",
			"Todos os civis no raio do Setor 17 devem dirigir-se à Autoestrada 9 até às 06:00. Os veículos particulares serão abandonados no posto. É uma precaução. Não há perigo para o público. — Autoridade Regional. (Rabiscado por baixo: fecharam a estrada às 05:00.)"],
	"m01_i2_title": ["Guard's Logbook", "Diário do Guarda"],
	"m01_i2_body": ["Day 1: sealed the gate. Day 3: shouting from inside, then nothing. Day 9: orders say nobody comes out, not even ours. Day 12: something scratching at the containers all night. Day 14: Pruitt went over the wall to look. Day 15: Pruitt came back. He isn't Pruitt.",
			"Dia 1: selámos o portão. Dia 3: gritos lá dentro, depois nada. Dia 9: as ordens dizem que ninguém sai, nem os nossos. Dia 12: algo a arranhar os contentores a noite toda. Dia 14: o Pruitt saltou o muro para ver. Dia 15: o Pruitt voltou. Não é o Pruitt."],
	"m01_i3_title": ["Echo Team Manifest", "Lista da Equipa Echo"],
	"m01_i3_body": ["ECHO: Lt. S. Okafor (lead), Sgt. D. Brandt, Cpl. A. Ruiz, Spc. T. Kim. Tasking: CLASSIFIED — see Col. A. Hale. Equipment: body cameras, sample containment cases x4. (Why would a recon team carry sample cases?)",
			"ECHO: Ten. S. Okafor (chefe), Sgt. D. Brandt, Cabo A. Ruiz, Esp. T. Kim. Missão: CONFIDENCIAL — ver Cor. A. Hale. Equipamento: câmaras corporais, caixas de contenção de amostras x4. (Porque levaria uma equipa de reconhecimento caixas de amostras?)"],
}


## Registers all languages with Godot's TranslationServer.
static func install() -> void:
	for i in LANGUAGES.size():
		var translation := Translation.new()
		translation.locale = LANGUAGES[i][0]
		for key: String in TEXT:
			translation.add_message(key, TEXT[key][i])
		TranslationServer.add_translation(translation)


## The player's system language if the game has it, otherwise English.
static func system_language() -> String:
	var lang := OS.get_locale_language()
	for entry in LANGUAGES:
		if entry[0] == lang:
			return lang
	return "en"
